# **Import Library**

In [ ]:
# ============================================================
# CELL 1: IMPORT LIBRARY
# ============================================================

import pandas as pd
import numpy as np
import os
from google.colab import files
from sqlalchemy import create_engine

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

print("Library berhasil di-import.")

Library berhasil di-import.

# **Extract Data**

In [ ]:
# ============================================================
# CELL 2: UPLOAD DATASET CSV
# ============================================================

uploaded = files.upload()

print("File yang berhasil diupload:")
for filename in uploaded.keys():
    print("-", filename)

Saving apotek.csv to apotek.csv
Saving karyawan.csv to karyawan.csv
Saving pelanggan.csv to pelanggan.csv
Saving penjualan.csv to penjualan.csv
Saving produk.csv to produk.csv
Saving supplier.csv to supplier.csv
File yang berhasil diupload:
- apotek.csv
- karyawan.csv
- pelanggan.csv
- penjualan.csv
- produk.csv
- supplier.csv

In [ ]:
# ============================================================
# CELL 3: LOAD DATASET
# ============================================================

produk = pd.read_csv("produk.csv")
apotek = pd.read_csv("apotek.csv")
pelanggan = pd.read_csv("pelanggan.csv")
karyawan = pd.read_csv("karyawan.csv")
supplier = pd.read_csv("supplier.csv")
penjualan = pd.read_csv("penjualan.csv")

datasets = {
    "produk": produk,
    "apotek": apotek,
    "pelanggan": pelanggan,
    "karyawan": karyawan,
    "supplier": supplier,
    "penjualan": penjualan
}

for name, df in datasets.items():
    print(f"\nDataset: {name}")
    print("Shape:", df.shape)
    display(df.head())

Dataset: produk
Shape: (120, 10)

,ProdukID,KodeProduk,NamaProduk,KategoriProduk,JenisProduk,Brand,SupplierID,HargaModal,HargaSatuanDefault,MarginDefault
0,PRD001,KF-P0001,Gel Nyeri Otot Forte,Obat Bebas,Tablet,Kimia Farma,SUP034,25500,32000,0.25
1,PRD002,KF-P0002,Termometer Digital,Obat Bebas,Salep,NaturaFit,SUP078,43000,51500,0.20
2,PRD003,KF-P0003,Gel Nyeri Otot Care,Obat Bebas,Salep,CareOne,SUP006,27000,32000,0.18
3,PRD004,KF-P0004,Termometer Digital Family,Obat Bebas,Sirup,AlkesPro,SUP043,11500,15000,0.30
4,PRD005,KF-P0005,Tensimeter Digital Forte,Vitamin & Suplemen,Tablet,CareOne,SUP086,67500,79500,0.18

Dataset: apotek
Shape: (100, 8)

  ApotekID KodeApotek              NamaApotek      Kota          Provinsi Wilayah           TipeCabang StatusCabang
0   APT001  KF-BEK001    Kimia Farma Bekasi 1    Bekasi        Jawa Barat   Barat              Reguler        Aktif
1   APT002  KF-BAN002   Kimia Farma Bandung 2   Bandung        Jawa Barat   Barat  Klinik Terintegrasi        Aktif
2   APT003  KF-MAK003  Kimia Farma Makassar 3  Makassar  Sulawesi Selatan   Timur  Klinik Terintegrasi        Aktif
3   APT004  KF-DEP004     Kimia Farma Depok 4     Depok        Jawa Barat   Barat  Klinik Terintegrasi        Aktif
4   APT005  KF-BOG005     Kimia Farma Bogor 5     Bogor        Jawa Barat   Barat      Mall/Commercial        Aktif

Dataset: pelanggan
Shape: (150, 9)

,PelangganID,KodePelanggan,NamaPelanggan,JenisKelamin,Usia,KelompokUsia,Kota,Provinsi,TipePelanggan
0,PLG001,CUST00001,Sinta Hidayat,P,28,25-35,Surakarta,Jawa Tengah,Member
1,PLG002,CUST00002,Citra Santoso,P,25,25-35,Semarang,Jawa Tengah,Member
2,PLG003,CUST00003,Arif Lestari,L,66,56+,Padang,Sumatera Barat,BPJS/Asuransi
3,PLG004,CUST00004,Doni Pangestu,L,55,46-55,Bogor,Jawa Barat,Corporate
4,PLG005,CUST00005,Fajar Ramadhan,L,68,56+,Balikpapan,Kalimantan Timur,Member

Dataset: karyawan
Shape: (120, 8)

  KaryawanID          NIK   NamaKaryawan JenisKelamin           Jabatan          Departemen ApotekID StatusKepegawaian
0     KRY001  KF202600001  Ilham Saputra            L      Admin Cabang        Administrasi   APT053            Magang
1     KRY002  KF202600002    Fikri Utami            L  Asisten Apoteker             Farmasi   APT027           Kontrak
2     KRY003  KF202600003  Ilham Hidayat            L             Kasir  Operasional Apotek   APT069             Tetap
3     KRY004  KF202600004   Hendra Fauzi            L      Admin Cabang        Administrasi   APT078             Tetap
4     KRY005  KF202600005   Bayu Azzahra            L      Admin Cabang        Administrasi   APT028            Magang

Dataset: supplier
Shape: (100, 6)

  SupplierID          NamaSupplier   KotaSupplier  ProvinsiSupplier WilayahSupplier     KategoriSupplier
0     SUP001   PT Herbal Nusantara     Yogyakarta     DI Yogyakarta          Tengah           Obat Bebas
1     SUP002  PT Sentosa Sejahtera         Bekasi        Jawa Barat           Barat  Perawatan Kesehatan
2     SUP003     PT Vita Indonesia       Makassar  Sulawesi Selatan           Timur       Alat Kesehatan
3     SUP004   PT Medika Nusantara  Jakarta Timur       DKI Jakarta           Barat           Obat Bebas
4     SUP005       PT Sentosa Jaya     Balikpapan  Kalimantan Timur           Timur         Obat Generik

Dataset: penjualan
Shape: (1000, 14)

,FakturID,Tanggal,ProdukID,ApotekID,PelangganID,KaryawanID,SupplierID,JumlahTerjual,HargaSatuan,Diskon,TotalPenjualan,Keuntungan,MetodePembayaran,ChannelTransaksi
0,FKT00001,2026-07-04,PRD012,APT087,PLG146,KRY077,SUP054,2,15500,0,31000,7000,Kredit,Apotek Ritel Internal
1,FKT00002,2026-04-01,PRD030,APT004,PLG016,KRY071,SUP084,2,16500,1600,31400,8400,Kredit,Apotek Ritel Internal
2,FKT00003,2026-08-05,PRD007,APT054,PLG040,KRY079,SUP073,1,30500,0,30500,5500,QRIS,Apotek Ritel Internal
3,FKT00004,2026-03-21,PRD046,APT065,PLG017,KRY033,SUP085,3,41000,18400,104600,2600,QRIS,Apotek Ritel Internal
4,FKT00005,2026-11-04,PRD052,APT061,PLG080,KRY086,SUP006,4,23500,0,94000,18000,Tunai,Apotek Ritel Internal

In [ ]:
# ============================================================
# CELL 4: DATA UNDERSTANDING
# ============================================================

for name, df in datasets.items():
    print("=" * 80)
    print(f"INFO DATASET: {name.upper()}")
    print("=" * 80)

    print("\nKolom:")
    print(df.columns.tolist())

    print("\nJumlah baris dan kolom:")
    print(df.shape)

    print("\nTipe data:")
    print(df.dtypes)

    print("\nMissing value:")
    print(df.isnull().sum())

    print("\nJumlah duplikasi:")
    print(df.duplicated().sum())

    print("\nPreview:")
    display(df.head())

================================================================================
INFO DATASET: PRODUK
================================================================================

Kolom:
['ProdukID', 'KodeProduk', 'NamaProduk', 'KategoriProduk', 'JenisProduk', 'Brand', 'SupplierID', 'HargaModal', 'HargaSatuanDefault', 'MarginDefault']

Jumlah baris dan kolom:
(120, 10)

Tipe data:
ProdukID               object
KodeProduk             object
NamaProduk             object
KategoriProduk         object
JenisProduk            object
Brand                  object
SupplierID             object
HargaModal              int64
HargaSatuanDefault      int64
MarginDefault         float64
dtype: object

Missing value:
ProdukID              0
KodeProduk            0
NamaProduk            0
KategoriProduk        0
JenisProduk           0
Brand                 0
SupplierID            0
HargaModal            0
HargaSatuanDefault    0
MarginDefault         0
dtype: int64

Jumlah duplikasi:
0

Preview:

,ProdukID,KodeProduk,NamaProduk,KategoriProduk,JenisProduk,Brand,SupplierID,HargaModal,HargaSatuanDefault,MarginDefault
0,PRD001,KF-P0001,Gel Nyeri Otot Forte,Obat Bebas,Tablet,Kimia Farma,SUP034,25500,32000,0.25
1,PRD002,KF-P0002,Termometer Digital,Obat Bebas,Salep,NaturaFit,SUP078,43000,51500,0.20
2,PRD003,KF-P0003,Gel Nyeri Otot Care,Obat Bebas,Salep,CareOne,SUP006,27000,32000,0.18
3,PRD004,KF-P0004,Termometer Digital Family,Obat Bebas,Sirup,AlkesPro,SUP043,11500,15000,0.30
4,PRD005,KF-P0005,Tensimeter Digital Forte,Vitamin & Suplemen,Tablet,CareOne,SUP086,67500,79500,0.18

================================================================================
INFO DATASET: APOTEK
================================================================================

Kolom:
['ApotekID', 'KodeApotek', 'NamaApotek', 'Kota', 'Provinsi', 'Wilayah', 'TipeCabang', 'StatusCabang']

Jumlah baris dan kolom:
(100, 8)

Tipe data:
ApotekID        object
KodeApotek      object
NamaApotek      object
Kota            object
Provinsi        object
Wilayah         object
TipeCabang      object
StatusCabang    object
dtype: object

Missing value:
ApotekID        0
KodeApotek      0
NamaApotek      0
Kota            0
Provinsi        0
Wilayah         0
TipeCabang      0
StatusCabang    0
dtype: int64

Jumlah duplikasi:
0

Preview:

  ApotekID KodeApotek              NamaApotek      Kota          Provinsi Wilayah           TipeCabang StatusCabang
0   APT001  KF-BEK001    Kimia Farma Bekasi 1    Bekasi        Jawa Barat   Barat              Reguler        Aktif
1   APT002  KF-BAN002   Kimia Farma Bandung 2   Bandung        Jawa Barat   Barat  Klinik Terintegrasi        Aktif
2   APT003  KF-MAK003  Kimia Farma Makassar 3  Makassar  Sulawesi Selatan   Timur  Klinik Terintegrasi        Aktif
3   APT004  KF-DEP004     Kimia Farma Depok 4     Depok        Jawa Barat   Barat  Klinik Terintegrasi        Aktif
4   APT005  KF-BOG005     Kimia Farma Bogor 5     Bogor        Jawa Barat   Barat      Mall/Commercial        Aktif

================================================================================
INFO DATASET: PELANGGAN
================================================================================

Kolom:
['PelangganID', 'KodePelanggan', 'NamaPelanggan', 'JenisKelamin', 'Usia', 'KelompokUsia', 'Kota', 'Provinsi', 'TipePelanggan']

Jumlah baris dan kolom:
(150, 9)

Tipe data:
PelangganID      object
KodePelanggan    object
NamaPelanggan    object
JenisKelamin     object
Usia              int64
KelompokUsia     object
Kota             object
Provinsi         object
TipePelanggan    object
dtype: object

Missing value:
PelangganID      0
KodePelanggan    0
NamaPelanggan    0
JenisKelamin     0
Usia             0
KelompokUsia     0
Kota             0
Provinsi         0
TipePelanggan    0
dtype: int64

Jumlah duplikasi:
0

Preview:

,PelangganID,KodePelanggan,NamaPelanggan,JenisKelamin,Usia,KelompokUsia,Kota,Provinsi,TipePelanggan
0,PLG001,CUST00001,Sinta Hidayat,P,28,25-35,Surakarta,Jawa Tengah,Member
1,PLG002,CUST00002,Citra Santoso,P,25,25-35,Semarang,Jawa Tengah,Member
2,PLG003,CUST00003,Arif Lestari,L,66,56+,Padang,Sumatera Barat,BPJS/Asuransi
3,PLG004,CUST00004,Doni Pangestu,L,55,46-55,Bogor,Jawa Barat,Corporate
4,PLG005,CUST00005,Fajar Ramadhan,L,68,56+,Balikpapan,Kalimantan Timur,Member

================================================================================
INFO DATASET: KARYAWAN
================================================================================

Kolom:
['KaryawanID', 'NIK', 'NamaKaryawan', 'JenisKelamin', 'Jabatan', 'Departemen', 'ApotekID', 'StatusKepegawaian']

Jumlah baris dan kolom:
(120, 8)

Tipe data:
KaryawanID           object
NIK                  object
NamaKaryawan         object
JenisKelamin         object
Jabatan              object
Departemen           object
ApotekID             object
StatusKepegawaian    object
dtype: object

Missing value:
KaryawanID           0
NIK                  0
NamaKaryawan         0
JenisKelamin         0
Jabatan              0
Departemen           0
ApotekID             0
StatusKepegawaian    0
dtype: int64

Jumlah duplikasi:
0

Preview:

  KaryawanID          NIK   NamaKaryawan JenisKelamin           Jabatan          Departemen ApotekID StatusKepegawaian
0     KRY001  KF202600001  Ilham Saputra            L      Admin Cabang        Administrasi   APT053            Magang
1     KRY002  KF202600002    Fikri Utami            L  Asisten Apoteker             Farmasi   APT027           Kontrak
2     KRY003  KF202600003  Ilham Hidayat            L             Kasir  Operasional Apotek   APT069             Tetap
3     KRY004  KF202600004   Hendra Fauzi            L      Admin Cabang        Administrasi   APT078             Tetap
4     KRY005  KF202600005   Bayu Azzahra            L      Admin Cabang        Administrasi   APT028            Magang

================================================================================
INFO DATASET: SUPPLIER
================================================================================

Kolom:
['SupplierID', 'NamaSupplier', 'KotaSupplier', 'ProvinsiSupplier', 'WilayahSupplier', 'KategoriSupplier']

Jumlah baris dan kolom:
(100, 6)

Tipe data:
SupplierID          object
NamaSupplier        object
KotaSupplier        object
ProvinsiSupplier    object
WilayahSupplier     object
KategoriSupplier    object
dtype: object

Missing value:
SupplierID          0
NamaSupplier        0
KotaSupplier        0
ProvinsiSupplier    0
WilayahSupplier     0
KategoriSupplier    0
dtype: int64

Jumlah duplikasi:
0

Preview:

  SupplierID          NamaSupplier   KotaSupplier  ProvinsiSupplier WilayahSupplier     KategoriSupplier
0     SUP001   PT Herbal Nusantara     Yogyakarta     DI Yogyakarta          Tengah           Obat Bebas
1     SUP002  PT Sentosa Sejahtera         Bekasi        Jawa Barat           Barat  Perawatan Kesehatan
2     SUP003     PT Vita Indonesia       Makassar  Sulawesi Selatan           Timur       Alat Kesehatan
3     SUP004   PT Medika Nusantara  Jakarta Timur       DKI Jakarta           Barat           Obat Bebas
4     SUP005       PT Sentosa Jaya     Balikpapan  Kalimantan Timur           Timur         Obat Generik

================================================================================
INFO DATASET: PENJUALAN
================================================================================

Kolom:
['FakturID', 'Tanggal', 'ProdukID', 'ApotekID', 'PelangganID', 'KaryawanID', 'SupplierID', 'JumlahTerjual', 'HargaSatuan', 'Diskon', 'TotalPenjualan', 'Keuntungan', 'MetodePembayaran', 'ChannelTransaksi']

Jumlah baris dan kolom:
(1000, 14)

Tipe data:
FakturID            object
Tanggal             object
ProdukID            object
ApotekID            object
PelangganID         object
KaryawanID          object
SupplierID          object
JumlahTerjual        int64
HargaSatuan          int64
Diskon               int64
TotalPenjualan       int64
Keuntungan           int64
MetodePembayaran    object
ChannelTransaksi    object
dtype: object

Missing value:
FakturID            0
Tanggal             0
ProdukID            0
ApotekID            0
PelangganID         0
KaryawanID          0
SupplierID          0
JumlahTerjual       0
HargaSatuan         0
Diskon              0
TotalPenjualan      0
Keuntungan          0
MetodePembayaran    0
ChannelTransaksi    0
dtype: int64

Jumlah duplikasi:
0

Preview:

,FakturID,Tanggal,ProdukID,ApotekID,PelangganID,KaryawanID,SupplierID,JumlahTerjual,HargaSatuan,Diskon,TotalPenjualan,Keuntungan,MetodePembayaran,ChannelTransaksi
0,FKT00001,2026-07-04,PRD012,APT087,PLG146,KRY077,SUP054,2,15500,0,31000,7000,Kredit,Apotek Ritel Internal
1,FKT00002,2026-04-01,PRD030,APT004,PLG016,KRY071,SUP084,2,16500,1600,31400,8400,Kredit,Apotek Ritel Internal
2,FKT00003,2026-08-05,PRD007,APT054,PLG040,KRY079,SUP073,1,30500,0,30500,5500,QRIS,Apotek Ritel Internal
3,FKT00004,2026-03-21,PRD046,APT065,PLG017,KRY033,SUP085,3,41000,18400,104600,2600,QRIS,Apotek Ritel Internal
4,FKT00005,2026-11-04,PRD052,APT061,PLG080,KRY086,SUP006,4,23500,0,94000,18000,Tunai,Apotek Ritel Internal

# **Transform**

In [ ]:
# ============================================================
# CELL 5: STANDARDISASI NAMA KOLOM
# ============================================================

def clean_column_names(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )
    return df

produk = clean_column_names(produk)
apotek = clean_column_names(apotek)
pelanggan = clean_column_names(pelanggan)
karyawan = clean_column_names(karyawan)
supplier = clean_column_names(supplier)
penjualan = clean_column_names(penjualan)

datasets = {
    "produk": produk,
    "apotek": apotek,
    "pelanggan": pelanggan,
    "karyawan": karyawan,
    "supplier": supplier,
    "penjualan": penjualan
}

for name, df in datasets.items():
    print(f"{name}: {df.columns.tolist()}")

produk: ['ProdukID', 'KodeProduk', 'NamaProduk', 'KategoriProduk', 'JenisProduk', 'Brand', 'SupplierID', 'HargaModal', 'HargaSatuanDefault', 'MarginDefault']
apotek: ['ApotekID', 'KodeApotek', 'NamaApotek', 'Kota', 'Provinsi', 'Wilayah', 'TipeCabang', 'StatusCabang']
pelanggan: ['PelangganID', 'KodePelanggan', 'NamaPelanggan', 'JenisKelamin', 'Usia', 'KelompokUsia', 'Kota', 'Provinsi', 'TipePelanggan']
karyawan: ['KaryawanID', 'NIK', 'NamaKaryawan', 'JenisKelamin', 'Jabatan', 'Departemen', 'ApotekID', 'StatusKepegawaian']
supplier: ['SupplierID', 'NamaSupplier', 'KotaSupplier', 'ProvinsiSupplier', 'WilayahSupplier', 'KategoriSupplier']
penjualan: ['FakturID', 'Tanggal', 'ProdukID', 'ApotekID', 'PelangganID', 'KaryawanID', 'SupplierID', 'JumlahTerjual', 'HargaSatuan', 'Diskon', 'TotalPenjualan', 'Keuntungan', 'MetodePembayaran', 'ChannelTransaksi']

In [ ]:
# ============================================================
# CELL 6: VALIDASI KOLOM WAJIB
# ============================================================

required_columns = {
    "produk": ["ProdukID"],
    "apotek": ["ApotekID"],
    "pelanggan": ["PelangganID"],
    "karyawan": ["KaryawanID"],
    "supplier": ["SupplierID"],
    "penjualan": [
        "FakturID",
        "Tanggal",
        "ProdukID",
        "ApotekID",
        "PelangganID",
        "KaryawanID",
        "SupplierID",
        "JumlahTerjual",
        "HargaSatuan",
        "Diskon"
    ]
}

for dataset_name, columns in required_columns.items():
    df = datasets[dataset_name]
    missing_cols = [col for col in columns if col not in df.columns]

    if missing_cols:
        print(f"[ERROR] Dataset {dataset_name} kekurangan kolom: {missing_cols}")
    else:
        print(f"[OK] Dataset {dataset_name} memiliki semua kolom wajib.")

[OK] Dataset produk memiliki semua kolom wajib.
[OK] Dataset apotek memiliki semua kolom wajib.
[OK] Dataset pelanggan memiliki semua kolom wajib.
[OK] Dataset karyawan memiliki semua kolom wajib.
[OK] Dataset supplier memiliki semua kolom wajib.
[OK] Dataset penjualan memiliki semua kolom wajib.

In [ ]:
# ============================================================
# CELL 7: DATA CLEANING DASAR
# ============================================================

def basic_cleaning(df):
    df = df.copy()

    # Hapus baris duplikat
    df = df.drop_duplicates()

    # Bersihkan spasi pada kolom bertipe string
    for col in df.select_dtypes(include=["object"]).columns:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace({"nan": np.nan, "None": np.nan, "": np.nan})

    return df

produk = basic_cleaning(produk)
apotek = basic_cleaning(apotek)
pelanggan = basic_cleaning(pelanggan)
karyawan = basic_cleaning(karyawan)
supplier = basic_cleaning(supplier)
penjualan = basic_cleaning(penjualan)

print("Cleaning dasar selesai.")

for name, df in {
    "produk": produk,
    "apotek": apotek,
    "pelanggan": pelanggan,
    "karyawan": karyawan,
    "supplier": supplier,
    "penjualan": penjualan
}.items():
    print(f"{name}: {df.shape}")

Cleaning dasar selesai.
produk: (120, 10)
apotek: (100, 8)
pelanggan: (150, 9)
karyawan: (120, 8)
supplier: (100, 6)
penjualan: (1000, 14)

In [ ]:
# ============================================================
# CELL 8: PERBAIKAN TIPE DATA
# ============================================================

# Ubah tanggal transaksi ke format datetime
penjualan["Tanggal"] = pd.to_datetime(penjualan["Tanggal"], errors="coerce")

# Kolom numerik pada transaksi
numeric_cols = ["JumlahTerjual", "HargaSatuan", "Diskon"]

for col in numeric_cols:
    if col in penjualan.columns:
        penjualan[col] = pd.to_numeric(penjualan[col], errors="coerce")

# Jika ada usia pelanggan, ubah ke numerik
if "Usia" in pelanggan.columns:
    pelanggan["Usia"] = pd.to_numeric(pelanggan["Usia"], errors="coerce")

print("Tipe data berhasil diperbaiki.")

print("\nTipe data penjualan:")
print(penjualan.dtypes)

print("\nPreview penjualan:")
display(penjualan.head())

Tipe data berhasil diperbaiki.

Tipe data penjualan:
FakturID                    object
Tanggal             datetime64[ns]
ProdukID                    object
ApotekID                    object
PelangganID                 object
KaryawanID                  object
SupplierID                  object
JumlahTerjual                int64
HargaSatuan                  int64
Diskon                       int64
TotalPenjualan               int64
Keuntungan                   int64
MetodePembayaran            object
ChannelTransaksi            object
dtype: object

Preview penjualan:

,FakturID,Tanggal,ProdukID,ApotekID,PelangganID,KaryawanID,SupplierID,JumlahTerjual,HargaSatuan,Diskon,TotalPenjualan,Keuntungan,MetodePembayaran,ChannelTransaksi
0,FKT00001,2026-07-04,PRD012,APT087,PLG146,KRY077,SUP054,2,15500,0,31000,7000,Kredit,Apotek Ritel Internal
1,FKT00002,2026-04-01,PRD030,APT004,PLG016,KRY071,SUP084,2,16500,1600,31400,8400,Kredit,Apotek Ritel Internal
2,FKT00003,2026-08-05,PRD007,APT054,PLG040,KRY079,SUP073,1,30500,0,30500,5500,QRIS,Apotek Ritel Internal
3,FKT00004,2026-03-21,PRD046,APT065,PLG017,KRY033,SUP085,3,41000,18400,104600,2600,QRIS,Apotek Ritel Internal
4,FKT00005,2026-11-04,PRD052,APT061,PLG080,KRY086,SUP006,4,23500,0,94000,18000,Tunai,Apotek Ritel Internal

In [ ]:
# ============================================================
# CELL 9: HANDLE MISSING VALUE
# ============================================================

# Hapus transaksi yang tidak punya ID penting atau tanggal
important_transaction_cols = [
    "FakturID",
    "Tanggal",
    "ProdukID",
    "ApotekID",
    "PelangganID",
    "KaryawanID",
    "SupplierID"
]

before_rows = len(penjualan)
penjualan = penjualan.dropna(subset=important_transaction_cols)
after_rows = len(penjualan)

print(f"Jumlah transaksi sebelum drop missing key: {before_rows}")
print(f"Jumlah transaksi setelah drop missing key: {after_rows}")

# Isi missing value numerik transaksi dengan 0 jika diperlukan
for col in ["JumlahTerjual", "HargaSatuan", "Diskon"]:
    if col in penjualan.columns:
        penjualan[col] = penjualan[col].fillna(0)

# Isi missing value pada dimensi dengan label Unknown
dimension_tables = [produk, apotek, pelanggan, karyawan, supplier]

for df in dimension_tables:
    for col in df.select_dtypes(include=["object"]).columns:
        df[col] = df[col].fillna("Unknown")

if "Usia" in pelanggan.columns:
    pelanggan["Usia"] = pelanggan["Usia"].fillna(pelanggan["Usia"].median())

print("\nMissing value setelah cleaning:")
print("Produk:")
print(produk.isnull().sum())
print("\nApotek:")
print(apotek.isnull().sum())
print("\nPelanggan:")
print(pelanggan.isnull().sum())
print("\nKaryawan:")
print(karyawan.isnull().sum())
print("\nSupplier:")
print(supplier.isnull().sum())
print("\nPenjualan:")
print(penjualan.isnull().sum())

Jumlah transaksi sebelum drop missing key: 1000
Jumlah transaksi setelah drop missing key: 1000

Missing value setelah cleaning:
Produk:
ProdukID              0
KodeProduk            0
NamaProduk            0
KategoriProduk        0
JenisProduk           0
Brand                 0
SupplierID            0
HargaModal            0
HargaSatuanDefault    0
MarginDefault         0
dtype: int64

Apotek:
ApotekID        0
KodeApotek      0
NamaApotek      0
Kota            0
Provinsi        0
Wilayah         0
TipeCabang      0
StatusCabang    0
dtype: int64

Pelanggan:
PelangganID      0
KodePelanggan    0
NamaPelanggan    0
JenisKelamin     0
Usia             0
KelompokUsia     0
Kota             0
Provinsi         0
TipePelanggan    0
dtype: int64

Karyawan:
KaryawanID           0
NIK                  0
NamaKaryawan         0
JenisKelamin         0
Jabatan              0
Departemen           0
ApotekID             0
StatusKepegawaian    0
dtype: int64

Supplier:
SupplierID          0
NamaSupplier        0
KotaSupplier        0
ProvinsiSupplier    0
WilayahSupplier     0
KategoriSupplier    0
dtype: int64

Penjualan:
FakturID            0
Tanggal             0
ProdukID            0
ApotekID            0
PelangganID         0
KaryawanID          0
SupplierID          0
JumlahTerjual       0
HargaSatuan         0
Diskon              0
TotalPenjualan      0
Keuntungan          0
MetodePembayaran    0
ChannelTransaksi    0
dtype: int64

In [ ]:
# ============================================================
# CELL 10: VALIDASI RELASI FOREIGN KEY
# ============================================================

def validate_foreign_key(fact_df, dim_df, fk_col, dim_key_col, dim_name):
    fact_keys = set(fact_df[fk_col].dropna().unique())
    dim_keys = set(dim_df[dim_key_col].dropna().unique())

    invalid_keys = fact_keys - dim_keys

    print(f"\nValidasi FK: {fk_col} → {dim_name}.{dim_key_col}")
    print(f"Jumlah key unik di fact: {len(fact_keys)}")
    print(f"Jumlah key unik di dimensi: {len(dim_keys)}")
    print(f"Jumlah key tidak valid: {len(invalid_keys)}")

    if len(invalid_keys) > 0:
        print("Contoh key tidak valid:", list(invalid_keys)[:10])
    else:
        print("[OK] Semua key valid.")

    return invalid_keys

invalid_produk = validate_foreign_key(penjualan, produk, "ProdukID", "ProdukID", "Dim_Produk")
invalid_apotek = validate_foreign_key(penjualan, apotek, "ApotekID", "ApotekID", "Dim_Apotek")
invalid_pelanggan = validate_foreign_key(penjualan, pelanggan, "PelangganID", "PelangganID", "Dim_Pelanggan")
invalid_karyawan = validate_foreign_key(penjualan, karyawan, "KaryawanID", "KaryawanID", "Dim_Karyawan")
invalid_supplier = validate_foreign_key(penjualan, supplier, "SupplierID", "SupplierID", "Dim_Supplier")

Validasi FK: ProdukID → Dim_Produk.ProdukID
Jumlah key unik di fact: 120
Jumlah key unik di dimensi: 120
Jumlah key tidak valid: 0
[OK] Semua key valid.

Validasi FK: ApotekID → Dim_Apotek.ApotekID
Jumlah key unik di fact: 100
Jumlah key unik di dimensi: 100
Jumlah key tidak valid: 0
[OK] Semua key valid.

Validasi FK: PelangganID → Dim_Pelanggan.PelangganID
Jumlah key unik di fact: 150
Jumlah key unik di dimensi: 150
Jumlah key tidak valid: 0
[OK] Semua key valid.

Validasi FK: KaryawanID → Dim_Karyawan.KaryawanID
Jumlah key unik di fact: 120
Jumlah key unik di dimensi: 120
Jumlah key tidak valid: 0
[OK] Semua key valid.

Validasi FK: SupplierID → Dim_Supplier.SupplierID
Jumlah key unik di fact: 71
Jumlah key unik di dimensi: 100
Jumlah key tidak valid: 0
[OK] Semua key valid.

In [ ]:
# ============================================================
# CELL 11: FILTER TRANSAKSI YANG VALID
# ============================================================

before_rows = len(penjualan)

penjualan = penjualan[
    penjualan["ProdukID"].isin(produk["ProdukID"]) &
    penjualan["ApotekID"].isin(apotek["ApotekID"]) &
    penjualan["PelangganID"].isin(pelanggan["PelangganID"]) &
    penjualan["KaryawanID"].isin(karyawan["KaryawanID"]) &
    penjualan["SupplierID"].isin(supplier["SupplierID"])
].copy()

after_rows = len(penjualan)

print(f"Jumlah transaksi sebelum filter FK valid: {before_rows}")
print(f"Jumlah transaksi setelah filter FK valid: {after_rows}")
print(f"Jumlah transaksi terhapus: {before_rows - after_rows}")

Jumlah transaksi sebelum filter FK valid: 1000
Jumlah transaksi setelah filter FK valid: 1000
Jumlah transaksi terhapus: 0

In [ ]:
# ============================================================
# CELL 12: MEMBUAT DIM_WAKTU
# ============================================================

dim_waktu = penjualan[["Tanggal"]].drop_duplicates().copy()

dim_waktu["WaktuID"] = dim_waktu["Tanggal"].dt.strftime("%Y%m%d").astype(int)
dim_waktu["Tanggal"] = dim_waktu["Tanggal"].dt.date
dim_waktu["Hari"] = pd.to_datetime(dim_waktu["Tanggal"]).dt.day_name()
dim_waktu["Bulan"] = pd.to_datetime(dim_waktu["Tanggal"]).dt.month_name()
dim_waktu["NomorBulan"] = pd.to_datetime(dim_waktu["Tanggal"]).dt.month
dim_waktu["Kuartal"] = "Q" + pd.to_datetime(dim_waktu["Tanggal"]).dt.quarter.astype(str)
dim_waktu["Tahun"] = pd.to_datetime(dim_waktu["Tanggal"]).dt.year

# Urutkan kolom
dim_waktu = dim_waktu[
    ["WaktuID", "Tanggal", "Hari", "Bulan", "NomorBulan", "Kuartal", "Tahun"]
].sort_values("WaktuID").reset_index(drop=True)

display(dim_waktu.head())
print("Jumlah baris Dim_Waktu:", len(dim_waktu))

    WaktuID     Tanggal       Hari    Bulan  NomorBulan Kuartal  Tahun
0  20260103  2026-01-03   Saturday  January           1      Q1   2026
1  20260104  2026-01-04     Sunday  January           1      Q1   2026
2  20260105  2026-01-05     Monday  January           1      Q1   2026
3  20260106  2026-01-06    Tuesday  January           1      Q1   2026
4  20260107  2026-01-07  Wednesday  January           1      Q1   2026

Jumlah baris Dim_Waktu: 336

In [ ]:
# ============================================================
# CELL 13: MEMBUAT DIM_PRODUK
# ============================================================

dim_produk = produk.copy()

# Hapus duplikasi berdasarkan ProdukID
dim_produk = dim_produk.drop_duplicates(subset=["ProdukID"])

# Pilih kolom yang relevan jika tersedia
produk_cols = [
    "ProdukID",
    "KodeProduk",
    "NamaProduk",
    "KategoriProduk",
    "JenisProduk",
    "Brand",
    "SupplierID",
    "HargaModal"
]

available_produk_cols = [col for col in produk_cols if col in dim_produk.columns]
dim_produk = dim_produk[available_produk_cols].copy()

display(dim_produk.head())
print("Jumlah baris Dim_Produk:", len(dim_produk))

  ProdukID KodeProduk                 NamaProduk      KategoriProduk JenisProduk        Brand SupplierID  HargaModal
0   PRD001   KF-P0001       Gel Nyeri Otot Forte          Obat Bebas      Tablet  Kimia Farma     SUP034       25500
1   PRD002   KF-P0002         Termometer Digital          Obat Bebas       Salep    NaturaFit     SUP078       43000
2   PRD003   KF-P0003        Gel Nyeri Otot Care          Obat Bebas       Salep      CareOne     SUP006       27000
3   PRD004   KF-P0004  Termometer Digital Family          Obat Bebas       Sirup     AlkesPro     SUP043       11500
4   PRD005   KF-P0005   Tensimeter Digital Forte  Vitamin & Suplemen      Tablet      CareOne     SUP086       67500

Jumlah baris Dim_Produk: 120

In [ ]:
# ============================================================
# CELL 14: MEMBUAT DIM_APOTEK
# ============================================================

dim_apotek = apotek.copy()
dim_apotek = dim_apotek.drop_duplicates(subset=["ApotekID"])

apotek_cols = [
    "ApotekID",
    "KodeApotek",
    "NamaApotek",
    "Kota",
    "Provinsi",
    "Wilayah",
    "TipeCabang"
]

available_apotek_cols = [col for col in apotek_cols if col in dim_apotek.columns]
dim_apotek = dim_apotek[available_apotek_cols].copy()

display(dim_apotek.head())
print("Jumlah baris Dim_Apotek:", len(dim_apotek))

  ApotekID KodeApotek              NamaApotek      Kota          Provinsi Wilayah           TipeCabang
0   APT001  KF-BEK001    Kimia Farma Bekasi 1    Bekasi        Jawa Barat   Barat              Reguler
1   APT002  KF-BAN002   Kimia Farma Bandung 2   Bandung        Jawa Barat   Barat  Klinik Terintegrasi
2   APT003  KF-MAK003  Kimia Farma Makassar 3  Makassar  Sulawesi Selatan   Timur  Klinik Terintegrasi
3   APT004  KF-DEP004     Kimia Farma Depok 4     Depok        Jawa Barat   Barat  Klinik Terintegrasi
4   APT005  KF-BOG005     Kimia Farma Bogor 5     Bogor        Jawa Barat   Barat      Mall/Commercial

Jumlah baris Dim_Apotek: 100

In [ ]:
# ============================================================
# CELL 15: MEMBUAT DIM_PELANGGAN
# ============================================================

dim_pelanggan = pelanggan.copy()
dim_pelanggan = dim_pelanggan.drop_duplicates(subset=["PelangganID"])

# Tambahkan kelompok usia jika kolom Usia tersedia
if "Usia" in dim_pelanggan.columns:
    bins = [0, 17, 25, 35, 45, 55, 100]
    labels = ["<18", "18-25", "26-35", "36-45", "46-55", ">55"]
    dim_pelanggan["KelompokUsia"] = pd.cut(
        dim_pelanggan["Usia"],
        bins=bins,
        labels=labels,
        right=True
    )

pelanggan_cols = [
    "PelangganID",
    "KodePelanggan",
    "NamaPelanggan",
    "JenisKelamin",
    "Usia",
    "KelompokUsia",
    "Kota",
    "Provinsi",
    "TipePelanggan"
]

available_pelanggan_cols = [col for col in pelanggan_cols if col in dim_pelanggan.columns]
dim_pelanggan = dim_pelanggan[available_pelanggan_cols].copy()

display(dim_pelanggan.head())
print("Jumlah baris Dim_Pelanggan:", len(dim_pelanggan))

,PelangganID,KodePelanggan,NamaPelanggan,JenisKelamin,Usia,KelompokUsia,Kota,Provinsi,TipePelanggan
0,PLG001,CUST00001,Sinta Hidayat,P,28,26-35,Surakarta,Jawa Tengah,Member
1,PLG002,CUST00002,Citra Santoso,P,25,18-25,Semarang,Jawa Tengah,Member
2,PLG003,CUST00003,Arif Lestari,L,66,>55,Padang,Sumatera Barat,BPJS/Asuransi
3,PLG004,CUST00004,Doni Pangestu,L,55,46-55,Bogor,Jawa Barat,Corporate
4,PLG005,CUST00005,Fajar Ramadhan,L,68,>55,Balikpapan,Kalimantan Timur,Member

Jumlah baris Dim_Pelanggan: 150

In [ ]:
# ============================================================
# CELL 16: MEMBUAT DIM_KARYAWAN
# ============================================================

dim_karyawan = karyawan.copy()
dim_karyawan = dim_karyawan.drop_duplicates(subset=["KaryawanID"])

karyawan_cols = [
    "KaryawanID",
    "NIK",
    "NamaKaryawan",
    "Jabatan",
    "Departemen",
    "StatusKepegawaian",
    "ApotekID"
]

available_karyawan_cols = [col for col in karyawan_cols if col in dim_karyawan.columns]
dim_karyawan = dim_karyawan[available_karyawan_cols].copy()

display(dim_karyawan.head())
print("Jumlah baris Dim_Karyawan:", len(dim_karyawan))

  KaryawanID          NIK   NamaKaryawan           Jabatan          Departemen StatusKepegawaian ApotekID
0     KRY001  KF202600001  Ilham Saputra      Admin Cabang        Administrasi            Magang   APT053
1     KRY002  KF202600002    Fikri Utami  Asisten Apoteker             Farmasi           Kontrak   APT027
2     KRY003  KF202600003  Ilham Hidayat             Kasir  Operasional Apotek             Tetap   APT069
3     KRY004  KF202600004   Hendra Fauzi      Admin Cabang        Administrasi             Tetap   APT078
4     KRY005  KF202600005   Bayu Azzahra      Admin Cabang        Administrasi            Magang   APT028

Jumlah baris Dim_Karyawan: 120

In [ ]:
# ============================================================
# CELL 17: MEMBUAT DIM_SUPPLIER
# ============================================================

dim_supplier = supplier.copy()
dim_supplier = dim_supplier.drop_duplicates(subset=["SupplierID"])

supplier_cols = [
    "SupplierID",
    "NamaSupplier",
    "KotaSupplier"
]

available_supplier_cols = [col for col in supplier_cols if col in dim_supplier.columns]
dim_supplier = dim_supplier[available_supplier_cols].copy()

display(dim_supplier.head())
print("Jumlah baris Dim_Supplier:", len(dim_supplier))

  SupplierID          NamaSupplier   KotaSupplier
0     SUP001   PT Herbal Nusantara     Yogyakarta
1     SUP002  PT Sentosa Sejahtera         Bekasi
2     SUP003     PT Vita Indonesia       Makassar
3     SUP004   PT Medika Nusantara  Jakarta Timur
4     SUP005       PT Sentosa Jaya     Balikpapan

Jumlah baris Dim_Supplier: 100

In [ ]:
# ============================================================
# CELL 18: MEMBUAT FACT_PENJUALAN
# ============================================================

fact_penjualan = penjualan.copy()

# Buat WaktuID dari tanggal transaksi
fact_penjualan["WaktuID"] = fact_penjualan["Tanggal"].dt.strftime("%Y%m%d").astype(int)

# Hitung TotalPenjualan jika belum ada
if "TotalPenjualan" not in fact_penjualan.columns:
    fact_penjualan["TotalPenjualan"] = (
        fact_penjualan["JumlahTerjual"] * fact_penjualan["HargaSatuan"]
    ) - fact_penjualan["Diskon"]

# Pastikan total penjualan tidak negatif
fact_penjualan["TotalPenjualan"] = fact_penjualan["TotalPenjualan"].clip(lower=0)

# Hitung Keuntungan
# Jika HargaModal ada di dim_produk, join dulu untuk menghitung TotalModal
if "HargaModal" in dim_produk.columns:
    fact_penjualan = fact_penjualan.merge(
        dim_produk[["ProdukID", "HargaModal"]],
        on="ProdukID",
        how="left"
    )

    fact_penjualan["HargaModal"] = pd.to_numeric(fact_penjualan["HargaModal"], errors="coerce").fillna(0)
    fact_penjualan["TotalModal"] = fact_penjualan["JumlahTerjual"] * fact_penjualan["HargaModal"]
    fact_penjualan["Keuntungan"] = fact_penjualan["TotalPenjualan"] - fact_penjualan["TotalModal"]

else:
    # Jika tidak ada HargaModal, gunakan margin simulasi 25%
    fact_penjualan["Keuntungan"] = fact_penjualan["TotalPenjualan"] * 0.25

# Pilih kolom fact
fact_cols = [
    "FakturID",
    "WaktuID",
    "ProdukID",
    "ApotekID",
    "PelangganID",
    "KaryawanID",
    "SupplierID",
    "JumlahTerjual",
    "HargaSatuan",
    "Diskon",
    "TotalPenjualan",
    "Keuntungan"
]

available_fact_cols = [col for col in fact_cols if col in fact_penjualan.columns]
fact_penjualan = fact_penjualan[available_fact_cols].copy()

display(fact_penjualan.head())
print("Jumlah baris Fact_Penjualan:", len(fact_penjualan))

,FakturID,WaktuID,ProdukID,ApotekID,PelangganID,KaryawanID,SupplierID,JumlahTerjual,HargaSatuan,Diskon,TotalPenjualan,Keuntungan
0,FKT00001,20260704,PRD012,APT087,PLG146,KRY077,SUP054,2,15500,0,31000,7000
1,FKT00002,20260401,PRD030,APT004,PLG016,KRY071,SUP084,2,16500,1600,31400,8400
2,FKT00003,20260805,PRD007,APT054,PLG040,KRY079,SUP073,1,30500,0,30500,5500
3,FKT00004,20260321,PRD046,APT065,PLG017,KRY033,SUP085,3,41000,18400,104600,2600
4,FKT00005,20261104,PRD052,APT061,PLG080,KRY086,SUP006,4,23500,0,94000,18000

Jumlah baris Fact_Penjualan: 1000

In [ ]:
# ============================================================
# CELL 19: VALIDASI STAR SCHEMA
# ============================================================

print("Validasi jumlah data:")
print("Dim_Produk     :", dim_produk.shape)
print("Dim_Apotek     :", dim_apotek.shape)
print("Dim_Pelanggan  :", dim_pelanggan.shape)
print("Dim_Karyawan   :", dim_karyawan.shape)
print("Dim_Supplier   :", dim_supplier.shape)
print("Dim_Waktu      :", dim_waktu.shape)
print("Fact_Penjualan :", fact_penjualan.shape)

print("\nValidasi foreign key pada Fact_Penjualan:")

validate_foreign_key(fact_penjualan, dim_produk, "ProdukID", "ProdukID", "Dim_Produk")
validate_foreign_key(fact_penjualan, dim_apotek, "ApotekID", "ApotekID", "Dim_Apotek")
validate_foreign_key(fact_penjualan, dim_pelanggan, "PelangganID", "PelangganID", "Dim_Pelanggan")
validate_foreign_key(fact_penjualan, dim_karyawan, "KaryawanID", "KaryawanID", "Dim_Karyawan")
validate_foreign_key(fact_penjualan, dim_supplier, "SupplierID", "SupplierID", "Dim_Supplier")
validate_foreign_key(fact_penjualan, dim_waktu, "WaktuID", "WaktuID", "Dim_Waktu")

Validasi jumlah data:
Dim_Produk     : (120, 8)
Dim_Apotek     : (100, 7)
Dim_Pelanggan  : (150, 9)
Dim_Karyawan   : (120, 7)
Dim_Supplier   : (100, 3)
Dim_Waktu      : (336, 7)
Fact_Penjualan : (1000, 12)

Validasi foreign key pada Fact_Penjualan:

Validasi FK: ProdukID → Dim_Produk.ProdukID
Jumlah key unik di fact: 120
Jumlah key unik di dimensi: 120
Jumlah key tidak valid: 0
[OK] Semua key valid.

Validasi FK: ApotekID → Dim_Apotek.ApotekID
Jumlah key unik di fact: 100
Jumlah key unik di dimensi: 100
Jumlah key tidak valid: 0
[OK] Semua key valid.

Validasi FK: PelangganID → Dim_Pelanggan.PelangganID
Jumlah key unik di fact: 150
Jumlah key unik di dimensi: 150
Jumlah key tidak valid: 0
[OK] Semua key valid.

Validasi FK: KaryawanID → Dim_Karyawan.KaryawanID
Jumlah key unik di fact: 120
Jumlah key unik di dimensi: 120
Jumlah key tidak valid: 0
[OK] Semua key valid.

Validasi FK: SupplierID → Dim_Supplier.SupplierID
Jumlah key unik di fact: 71
Jumlah key unik di dimensi: 100
Jumlah key tidak valid: 0
[OK] Semua key valid.

Validasi FK: WaktuID → Dim_Waktu.WaktuID
Jumlah key unik di fact: 336
Jumlah key unik di dimensi: 336
Jumlah key tidak valid: 0
[OK] Semua key valid.

set()

In [ ]:
import pandas as pd
import numpy as np
import os

# ============================================================
# CELL 20: PREVIEW DATA ANALITIK HASIL JOIN
# ============================================================

analyical_df = fact_penjualan.copy()

analyical_df = analyical_df.merge(dim_produk, on="ProdukID", how="left", suffixes=('', '_Produk'))
analyical_df = analyical_df.merge(dim_apotek, on="ApotekID", how="left")
analyical_df = analyical_df.merge(dim_pelanggan, on="PelangganID", how="left", suffixes=("", "_Pelanggan"))
analyical_df = analyical_df.merge(dim_karyawan, on="KaryawanID", how="left", suffixes=("", "_Karyawan"))
analyical_df = analyical_df.merge(dim_supplier, on="SupplierID", how="left")
analyical_df = analyical_df.merge(dim_waktu, on="WaktuID", how="left")

print("Shape data analitik:", analyical_df.shape)
display(analyical_df.head())

Shape data analitik: (1000, 47)

,FakturID,WaktuID,ProdukID,ApotekID,PelangganID,KaryawanID,SupplierID,JumlahTerjual,HargaSatuan,Diskon,TotalPenjualan,Keuntungan,KodeProduk,NamaProduk,KategoriProduk,JenisProduk,Brand,SupplierID_Produk,HargaModal,KodeApotek,NamaApotek,Kota,Provinsi,Wilayah,TipeCabang,KodePelanggan,NamaPelanggan,JenisKelamin,Usia,KelompokUsia,Kota_Pelanggan,Provinsi_Pelanggan,TipePelanggan,NIK,NamaKaryawan,Jabatan,Departemen,StatusKepegawaian,ApotekID_Karyawan,NamaSupplier,KotaSupplier,Tanggal,Hari,Bulan,NomorBulan,Kuartal,Tahun
0,FKT00001,20260704,PRD012,APT087,PLG146,KRY077,SUP054,2,15500,0,31000,7000,KF-P0012,Multivitamin Anak Family,Obat Bebas,Tablet,AlkesPro,SUP054,12000,KF-JAK087,Kimia Farma Jakarta Selatan 87,Jakarta Selatan,DKI Jakarta,Barat,Mall/Commercial,CUST00146,Kevin Utami,L,36,36-45,Denpasar,Bali,Member,KF202600077,Gita Azzahra,Kasir,Operasional Apotek,Tetap,APT087,PT Indo Farma,Denpasar,2026-07-04,Saturday,July,7,Q3,2026
1,FKT00002,20260401,PRD030,APT004,PLG016,KRY071,SUP084,2,16500,1600,31400,8400,KF-P0030,Multivitamin Anak,Obat Bebas,Kapsul,Kimia Farma,SUP084,11500,KF-DEP004,Kimia Farma Depok 4,Depok,Jawa Barat,Barat,Klinik Terintegrasi,CUST00016,Doni Lestari,L,67,>55,Surabaya,Jawa Timur,Member,KF202600071,Fajar Amelia,Supervisor Cabang,Operasional Apotek,Tetap,APT004,PT Mitra Sejahtera,Yogyakarta,2026-04-01,Wednesday,April,4,Q2,2026
2,FKT00003,20260805,PRD007,APT054,PLG040,KRY079,SUP073,1,30500,0,30500,5500,KF-P0007,Plester Luka,Perawatan Kesehatan,Spray,HerbaNusa,SUP073,25000,KF-BOG054,Kimia Farma Bogor 54,Bogor,Jawa Barat,Barat,Klinik Terintegrasi,CUST00040,Wulan Saputra,P,56,>55,Malang,Jawa Timur,Corporate,KF202600079,Maya Oktavia,Supervisor Cabang,Operasional Apotek,Tetap,APT054,PT Mitra Mandiri,Yogyakarta,2026-08-05,Wednesday,August,8,Q3,2026
3,FKT00004,20260321,PRD046,APT065,PLG017,KRY033,SUP085,3,41000,18400,104600,2600,KF-P0046,Oralit Sachet,Vitamin & Suplemen,Kapsul,AlkesPro,SUP085,34000,KF-JAK065,Kimia Farma Jakarta Timur 65,Jakarta Timur,DKI Jakarta,Barat,Mall/Commercial,CUST00017,Budi Kusuma,L,61,>55,Palembang,Sumatera Selatan,Member,KF202600033,Tiara Permata,Kasir,Operasional Apotek,Kontrak,APT065,PT Anugerah Jaya,Denpasar,2026-03-21,Saturday,March,3,Q1,2026
4,FKT00005,20261104,PRD052,APT061,PLG080,KRY086,SUP006,4,23500,0,94000,18000,KF-P0052,Glukosa Test Strip Care,Vitamin & Suplemen,Tablet,Kimia Farma,SUP006,19000,KF-SUR061,Kimia Farma Surabaya 61,Surabaya,Jawa Timur,Timur,Mall/Commercial,CUST00080,Miko Mahendra,L,40,36-45,Tangerang,Banten,BPJS/Asuransi,KF202600086,Fitri Mahendra,Asisten Apoteker,Farmasi,Magang,APT022,PT Vita Mandiri,Pekanbaru,2026-11-04,Wednesday,November,11,Q4,2026

In [ ]:
# ============================================================
# CELL 21A: INSIGHT PRODUK TERLARIS
# ============================================================

produk_terlaris = (
    analyical_df
    .groupby("NamaProduk", as_index=False)
    .agg(
        Total_Terjual=("JumlahTerjual", "sum"),
        Total_Penjualan=("TotalPenjualan", "sum"),
        Total_Keuntungan=("Keuntungan", "sum")
    )
    .sort_values("Total_Penjualan", ascending=False)
    .head(10)
)

display(produk_terlaris)

                     NamaProduk  Total_Terjual  Total_Penjualan  Total_Keuntungan
48        Obat Flu Tablet Forte            142         11984300           2503800
66               Susu Kesehatan            102          7005300            891300
6   Asam Mefenamat 500mg Family             86          5868800            490800
23         Hand Sanitizer 100ml            105          5652200           1057700
21     Glukosa Test Strip Forte             83          5600800            634300
71           Termometer Digital             75          5035100            959100
55            Paracetamol 500mg             84          4758200            694200
20    Glukosa Test Strip Family             80          4632600            645100
62                  Salep Kulit             54          4579200            575200
64            Salep Kulit Forte             89          4070500            926500

In [ ]:
# ============================================================
# CELL 21B: INSIGHT PENJUALAN PER KOTA
# ============================================================

penjualan_kota = (
    analyical_df
    .groupby("Kota", as_index=False)
    .agg(
        Total_Penjualan=("TotalPenjualan", "sum"),
        Total_Keuntungan=("Keuntungan", "sum"),
        Jumlah_Transaksi=("FakturID", "count")
    )
    .sort_values("Total_Penjualan", ascending=False)
)

display(penjualan_kota.head(10))

               Kota  Total_Penjualan  Total_Keuntungan  Jumlah_Transaksi
7     Jakarta Timur         32652100           5231100               182
16         Surabaya         15124500           2550000               116
1           Bandung         13438600           2184600                98
6   Jakarta Selatan         13180300           2000300                94
11           Padang          9992200           1586200                64
2            Bekasi          9063100           1391600                74
8          Makassar          6642900           1142900                40
4          Denpasar          6642500           1101500                53
0        Balikpapan          6179700            977700                34
5             Depok          5630100           1016100                29

In [ ]:
# ============================================================
# CELL 21C: INSIGHT TREN PENJUALAN BULANAN
# ============================================================

tren_bulanan = (
    analyical_df
    .groupby(["Tahun", "NomorBulan", "Bulan"], as_index=False)
    .agg(
        Total_Penjualan=("TotalPenjualan", "sum"),
        Total_Keuntungan=("Keuntungan", "sum"),
        Jumlah_Transaksi=("FakturID", "count")
    )
    .sort_values(["Tahun", "NomorBulan"])
)

display(tren_bulanan)

    Tahun  NomorBulan      Bulan  Total_Penjualan  Total_Keuntungan  Jumlah_Transaksi
0    2026           1    January          7324200           1119700                54
1    2026           2   February          7525500           1285000                58
2    2026           3      March         10359400           1569400                70
3    2026           4      April         15708300           2430800               108
4    2026           5        May         16836900           2507900               106
5    2026           6       June         16362100           2721600               100
6    2026           7       July          7907300           1317800                56
7    2026           8     August         10286400           1709900                72
8    2026           9  September         10452900           1593900                73
9    2026          10    October          9596100           1411600                71
10   2026          11   November         17173100           2719600               117
11   2026          12   December         19807300           3490300               115

In [ ]:
# ============================================================
# CELL 21D: INSIGHT SUPPLIER
# ============================================================

supplier_performance = (
    analyical_df
    .groupby("NamaSupplier", as_index=False)
    .agg(
        Total_Penjualan=("TotalPenjualan", "sum"),
        Total_Keuntungan=("Keuntungan", "sum"),
        Jumlah_Produk_Terjual=("JumlahTerjual", "sum")
    )
    .sort_values("Total_Penjualan", ascending=False)
)

display(supplier_performance.head(10))

            NamaSupplier  Total_Penjualan  Total_Keuntungan  Jumlah_Produk_Terjual
39     PT Medika Mandiri          8384100           1770600                    102
57    PT Sehat Kesehatan          6930400           1497900                    116
34         PT Indo Utama          6414800            567800                    128
17        PT Farma Utama          6057500            785500                    136
59    PT Sentosa Mandiri          5904400            709400                    114
5       PT Anugerah Jaya          5643100            860100                    142
60  PT Sentosa Sejahtera          5611700            714700                     90
68        PT Vita Medika          4533400            490900                     55
42    PT Mitra Indonesia          4009700            658200                    103
61      PT Sentosa Utama          3783300            500300                     55

In [ ]:
# ============================================================
# CELL 21E: INSIGHT SEGMENTASI PELANGGAN
# ============================================================

if "KelompokUsia" in analyical_df.columns:
    segmentasi_usia = (
        analyical_df
        .groupby("KelompokUsia", as_index=False)
        .agg(
            Total_Penjualan=("TotalPenjualan", "sum"),
            Jumlah_Transaksi=("FakturID", "count")
        )
        .sort_values("Total_Penjualan", ascending=False)
    )

    display(segmentasi_usia)

if "JenisKelamin" in analyical_df.columns:
    segmentasi_gender = (
        analyical_df
        .groupby("JenisKelamin", as_index=False)
        .agg(
            Total_Penjualan=("TotalPenjualan", "sum"),
            Jumlah_Transaksi=("FakturID", "count")
        )
        .sort_values("Total_Penjualan", ascending=False)
    )

    display(segmentasi_gender)

/tmp/ipykernel_1562/3425646298.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("KelompokUsia", as_index=False)

  KelompokUsia  Total_Penjualan  Jumlah_Transaksi
5          >55         43383700               298
3        36-45         33382400               206
2        26-35         27918500               191
4        46-55         23474500               167
1        18-25         18770200               122
0          <18          2410200                16

  JenisKelamin  Total_Penjualan  Jumlah_Transaksi
1            P         88233200               553
0            L         61106300               447

In [ ]:
# ============================================================
# CELL 21F: INSIGHT 1 - DEMOGRAFI & PRODUK (LANSIA + BPJS)
# Kategori produk apa yang paling banyak dibeli lansia pakai BPJS?
# ============================================================

# Memastikan kolom yang dibutuhkan tersedia
if all(col in analyical_df.columns for col in ["KelompokUsia", "TipePelanggan", "KategoriProduk", "TotalPenjualan"]):

    filter_lansia_bpjs = analyical_df[
        (analyical_df["KelompokUsia"].astype(str).str.contains(">55", na=False)) &
        (analyical_df["TipePelanggan"].astype(str).str.contains("BPJS/Asuransi", na=False, case=False))
    ]

    insight_demografi_produk = (
        filter_lansia_bpjs
        .groupby("KategoriProduk", as_index=False)
        .agg(
            Total_Penjualan=("TotalPenjualan", "sum"),
            Jumlah_Transaksi=("FakturID", "count")
        )
        .sort_values("Total_Penjualan", ascending=False)
    )

    print("Insight 1: Produk Favorit Lansia (>55) Pengguna BPJS")
    display(insight_demografi_produk)

Insight 1: Produk Favorit Lansia (>55) Pengguna BPJS

        KategoriProduk  Total_Penjualan  Jumlah_Transaksi
2           Obat Bebas          2065900                13
5   Vitamin & Suplemen          1542900                12
0       Alat Kesehatan          1022100                11
4  Perawatan Kesehatan           787200                 4
1               Herbal           728500                 6
3         Obat Generik            71100                 1

In [ ]:
# ============================================================
# CELL 21G: INSIGHT 2 - GEOGRAFIS & PERFORMA CABANG
# Perbandingan margin (Keuntungan) Mall/Commercial vs Klinik di Jawa Barat
# ============================================================

if all(col in analyical_df.columns for col in ["Provinsi", "TipeCabang", "Keuntungan"]):

    filter_jabar_tipe = analyical_df[
        (analyical_df["Provinsi"].astype(str).str.contains("Jawa Barat", case=False, na=False)) &
        (analyical_df["TipeCabang"].isin(["Mall/Commercial", "Klinik Terintegrasi"]))
    ]

    insight_cabang_jabar = (
        filter_jabar_tipe
        .groupby("TipeCabang", as_index=False)
        .agg(
            Total_Keuntungan=("Keuntungan", "sum"),
            Rata_Rata_Keuntungan=("Keuntungan", "mean")
        )
        .sort_values("Total_Keuntungan", ascending=False)
    )

    print("Insight 2: Perbandingan Keuntungan Mall vs Klinik di Jawa Barat")
    display(insight_cabang_jabar)

Insight 2: Perbandingan Keuntungan Mall vs Klinik di Jawa Barat

            TipeCabang  Total_Keuntungan  Rata_Rata_Keuntungan
0  Klinik Terintegrasi           1593200          22439.436620
1      Mall/Commercial           1371400          22119.354839

In [ ]:
# ============================================================
# CELL 21H: INSIGHT 3 - ANALISIS RANTAI PASOK (SUPPLIER)
# Supplier dengan kontribusi margin terbesar pada Q3 tahun ini
# ============================================================

if all(col in analyical_df.columns for col in ["NamaSupplier", "Kuartal", "Tahun", "Keuntungan"]):

    tahun_terbaru = analyical_df["Tahun"].max()

    filter_q3_tahun_ini = analyical_df[
        (analyical_df["Kuartal"] == "Q3") &
        (analyical_df["Tahun"] == tahun_terbaru)
    ]

    insight_supplier_q3 = (
        filter_q3_tahun_ini
        .groupby("NamaSupplier", as_index=False)
        .agg(
            Total_Keuntungan=("Keuntungan", "sum"),
            Jumlah_Item_Disuplai=("JumlahTerjual", "sum")
        )
        .sort_values("Total_Keuntungan", ascending=False)
        .head(5)
    )

    print(f"Insight 3: Top 5 Supplier Berdasarkan Keuntungan di Q3 Tahun {tahun_terbaru}")
    display(insight_supplier_q3)

Insight 3: Top 5 Supplier Berdasarkan Keuntungan di Q3 Tahun 2026

          NamaSupplier  Total_Keuntungan  Jumlah_Item_Disuplai
34   PT Medika Mandiri            439600                    21
51  PT Sehat Kesehatan            307700                    20
5     PT Anugerah Jaya            280900                    51
28      PT Indo Medika            187500                    18
15  PT Farma Sejahtera            175000                    11

In [ ]:
# ============================================================
# CELL: QUERY SQL OLAP (DATA CUBE MENGGUNAKAN SQL)
# ============================================================
import pandas as pd

print("Menjalankan Query SQL OLAP menggunakan fungsi CUBE...")

# Query SQL OLAP dengan operasi CUBE untuk menghasilkan semua kombinasi agregasi
olap_sql_query = """
SELECT
    a."Wilayah",
    a."TipeCabang",
    w."Kuartal",
    SUM(f."TotalPenjualan") AS "Total_Penjualan",
    COUNT(f."FakturID") AS "Jumlah_Transaksi"
FROM fact_penjualan f
LEFT JOIN dim_apotek a ON f."ApotekID" = a."ApotekID"
LEFT JOIN dim_waktu w ON f."WaktuID" = w."WaktuID"
GROUP BY CUBE (a."Wilayah", a."TipeCabang", w."Kuartal")
ORDER BY
    a."Wilayah" NULLS LAST,
    a."TipeCabang" NULLS LAST,
    w."Kuartal" NULLS LAST;
"""

# Menjalankan query ke database Supabase (menggunakan objek engine yang sudah kamu buat sebelumnya)
try:
    df_olap_sql = pd.read_sql(olap_sql_query, con=engine)

    # Mengisi nilai NULL/None hasil operasi CUBE dengan label 'ALL' agar lebih mudah dibaca
    df_olap_sql["Wilayah"] = df_olap_sql["Wilayah"].fillna("ALL WILAYAH")
    df_olap_sql["TipeCabang"] = df_olap_sql["TipeCabang"].fillna("ALL TIPE")
    df_olap_sql["Kuartal"] = df_olap_sql["Kuartal"].fillna("ALL KUARTAL")

    # Format mata uang untuk kolom Total_Penjualan
    df_olap_sql["Total_Penjualan_Formatted"] = df_olap_sql["Total_Penjualan"].apply(lambda x: f"Rp {x:,.0f}".replace(",", "."))

    # Menampilkan 20 baris pertama sebagai sampel kuadrat data
    display(df_olap_sql[["Wilayah", "TipeCabang", "Kuartal", "Total_Penjualan_Formatted", "Jumlah_Transaksi"]].head(20))

except Exception as e:
    print("Gagal menjalankan query OLAP. Pastikan tabel di database sudah terisi.")
    print("Error:", e)

Menjalankan Query SQL OLAP menggunakan fungsi CUBE...

   Wilayah           TipeCabang      Kuartal Total_Penjualan_Formatted  Jumlah_Transaksi
0    Barat  Klinik Terintegrasi           Q1              Rp 3.827.600                23
1    Barat  Klinik Terintegrasi           Q2              Rp 9.324.700                58
2    Barat  Klinik Terintegrasi           Q3              Rp 4.367.000                36
3    Barat  Klinik Terintegrasi           Q4              Rp 7.290.600                52
4    Barat  Klinik Terintegrasi  ALL KUARTAL             Rp 24.809.900               169
5    Barat      Mall/Commercial           Q1              Rp 3.810.400                34
6    Barat      Mall/Commercial           Q2             Rp 12.075.800                63
7    Barat      Mall/Commercial           Q3              Rp 5.878.100                36
8    Barat      Mall/Commercial           Q4              Rp 6.673.200                44
9    Barat      Mall/Commercial  ALL KUARTAL             Rp 28.437.500               177
10   Barat                Prime           Q1              Rp 6.790.000                38
11   Barat                Prime           Q2              Rp 5.957.900                45
12   Barat                Prime           Q3              Rp 4.509.800                32
13   Barat                Prime           Q4              Rp 8.344.200                56
14   Barat                Prime  ALL KUARTAL             Rp 25.601.900               171
15   Barat              Reguler           Q1              Rp 3.356.600                26
16   Barat              Reguler           Q2              Rp 5.030.700                34
17   Barat              Reguler           Q3              Rp 3.375.700                22
18   Barat              Reguler           Q4              Rp 5.561.100                37
19   Barat              Reguler  ALL KUARTAL             Rp 17.324.100               119

In [ ]:
# ============================================================
# CELL 22: LOAD / EXPORT HASIL ETL
# ============================================================

output_dir = "data_warehouse"
os.makedirs(output_dir, exist_ok=True)

dim_produk.to_csv(f"{output_dir}/dim_produk.csv", index=False)
dim_apotek.to_csv(f"{output_dir}/dim_apotek.csv", index=False)
dim_pelanggan.to_csv(f"{output_dir}/dim_pelanggan.csv", index=False)
dim_karyawan.to_csv(f"{output_dir}/dim_karyawan.csv", index=False)
dim_supplier.to_csv(f"{output_dir}/dim_supplier.csv", index=False)
dim_waktu.to_csv(f"{output_dir}/dim_waktu.csv", index=False)
fact_penjualan.to_csv(f"{output_dir}/fact_penjualan.csv", index=False)

print("Output ETL berhasil disimpan di folder:", output_dir)
print(os.listdir(output_dir))

Output ETL berhasil disimpan di folder: data_warehouse
['fact_penjualan.csv', 'dim_karyawan.csv', 'dim_produk.csv', 'dim_pelanggan.csv', 'dim_supplier.csv', 'dim_waktu.csv', 'dim_apotek.csv']

In [ ]:
# 1. Masukkan Connection String dari Supabase
DB_URL = "postgresql://postgres.hudffdkqzckfayxpslun:Proyek_Datwer@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres"

# 2. Buat Engine Koneksi
engine = create_engine(DB_URL)

# 3. Load DataFrame ke Supabase sebagai Tabel SQL
# Gunakan if_exists='replace' agar tabel lama diganti kalau kamu run ulang IPYNB-nya
dim_pelanggan.to_sql('dim_pelanggan', engine, if_exists='replace', index=False)
dim_produk.to_sql('dim_produk', engine, if_exists='replace', index=False)
dim_apotek.to_sql('dim_apotek', engine, if_exists='replace', index=False)
dim_waktu.to_sql('dim_waktu', engine, if_exists='replace', index=False)
dim_karyawan.to_sql('dim_karyawan', engine, if_exists='replace', index=False) # Tadi salah ketik 'dim_apotek'
dim_supplier.to_sql('dim_supplier', engine, if_exists='replace', index=False) # Tadi salah ketik 'dim_waktu'
fact_penjualan.to_sql('fact_penjualan', engine, if_exists='replace', index=False)

print("Berhasil Export ke Supabase SQL!")

Berhasil Export ke Supabase SQL!

In [ ]:
# ============================================================
# CELL 23: ZIP DAN DOWNLOAD OUTPUT ETL
# ============================================================

import shutil

zip_name = "kimia_farma_data_warehouse_output"
shutil.make_archive(zip_name, "zip", output_dir)

files.download(f"{zip_name}.zip")

print("File ZIP siap didownload.")

File ZIP siap didownload.