# **Import Library**

In [1]:
# ============================================================
# CELL 1: IMPORT LIBRARY
# ============================================================

import pandas as pd
import numpy as np
import os
from google.colab import files
from sqlalchemy import create_engine

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

print("Library berhasil di-import.")

Library berhasil di-import.

In [2]:
# ============================================================
# LINGKUNGAN CLEANING: HAPUS FILE CSV LAMA & RESET MEMORI
# ============================================================
import os
import gc

print("=== MEMULAI PEMBERSIHAN LINGKUNGAN COLAB ===")

# 1. Daftar nama file dasar dan pola duplikat otomatis dari Google Colab
base_files = ["penjualan", "produk", "apotek", "pelanggan", "karyawan", "supplier"]
deleted_files_count = 0

# Looping untuk mencari file asli maupun file duplikat seperti penjualan (1).csv, penjualan (2).csv, dll.
for base in base_files:
    # Cek file utama (misal: penjualan.csv)
    main_file = f"{base}.csv"
    if os.path.exists(main_file):
        os.remove(main_file)
        print(f"[HAPUS] File utama '{main_file}' berhasil dibersihkan.")
        deleted_files_count += 1

    # Cek duplikat otomatis dari Colab dari indeks 1 sampai 10 (misal: penjualan (1).csv)
    for i in range(1, 11):
        duplicate_file = f"{base} ({i}).csv"
        if os.path.exists(duplicate_file):
            os.remove(duplicate_file)
            print(f"[HAPUS] File duplikat '{duplicate_file}' berhasil dibersihkan.")
            deleted_files_count += 1

if deleted_files_count == 0:
    print("[INFO] Tidak ditemukan file CSV lama di direktori. Lingkungan sudah bersih.")
else:
    print(f"[INFO] Sukses menghapus total {deleted_files_count} file CSV lama dari penyimpanan.")

# 2. Menghapus variabel internal lama dari RAM Google Colab agar tidak bentrok
old_variables = [
    'penjualan', 'produk', 'apotek', 'pelanggan', 'karyawan', 'supplier', 'datasets',
    'dim_produk', 'dim_apotek', 'dim_pelanggan', 'dim_karyawan', 'dim_supplier', 'dim_waktu', 'fact_penjualan'
]

reset_vars_count = 0
for var in old_variables:
    if var in globals():
        del globals()[var]
        reset_vars_count += 1

# Paksa Python untuk mengosongkan RAM yang tersisa
gc.collect()

print(f"[INFO] Sukses me-reset {reset_vars_count} variabel lama dari memori RAM Python.")
print("\n[STATUS] 👍 Google Colab 100% STERIL! Silakan upload file-file CSV barumu sekarang.")

=== MEMULAI PEMBERSIHAN LINGKUNGAN COLAB ===
[INFO] Tidak ditemukan file CSV lama di direktori. Lingkungan sudah bersih.
[INFO] Sukses me-reset 0 variabel lama dari memori RAM Python.

[STATUS] 👍 Google Colab 100% STERIL! Silakan upload file-file CSV barumu sekarang.

# **Extract Data**

In [3]:
# ============================================================
# CELL 2: UPLOAD DATASET CSV
# ============================================================

uploaded = files.upload()

print("File yang berhasil diupload:")
for filename in uploaded.keys():
    print("-", filename)

Saving apotek.csv to apotek.csv
Saving karyawan.csv to karyawan.csv
Saving pelanggan.csv to pelanggan.csv
Saving penjualan.csv to penjualan.csv
Saving produk.csv to produk.csv
Saving supplier.csv to supplier.csv
File yang berhasil diupload:
- apotek.csv
- karyawan.csv
- pelanggan.csv
- penjualan.csv
- produk.csv
- supplier.csv

In [4]:
# ============================================================
# CELL 3: LOAD DATASET
# ============================================================

produk = pd.read_csv("produk.csv")
apotek = pd.read_csv("apotek.csv")
pelanggan = pd.read_csv("pelanggan.csv")
karyawan = pd.read_csv("karyawan.csv")
supplier = pd.read_csv("supplier.csv")
penjualan = pd.read_csv("penjualan.csv")

datasets = {
    "produk": produk,
    "apotek": apotek,
    "pelanggan": pelanggan,
    "karyawan": karyawan,
    "supplier": supplier,
    "penjualan": penjualan
}

for name, df in datasets.items():
    print(f"\nDataset: {name}")
    print("Shape:", df.shape)
    display(df.head())

Dataset: produk
Shape: (120, 10)

,ProdukID,KodeProduk,Nama Produk,KategoriProduk,JenisProduk,Brand,SupplierID,HargaModal,HargaSatuanDefault,MarginDefault
0,prd001,KF-P0001,Gel Nyeri Otot Forte,Obat Bebas,Tablet,Kimia Farma,SUP034,25500,32000,0.25
1,PRD002,KF-P0002,Termometer Digital,Obat Bebas,Salep,NaturaFit,SUP078,43000,51500,0.20
2,PRD003,KF-P0003,Gel Nyeri Otot Care,Obat Bebas,Salep,CareOne,SUP006,27000,32000,0.18
3,PRD004,KF-P0004,Termometer Digital Family,Obat Bebas,Sirup,AlkesPro,SUP043,11500,15000,0.30
4,PRD005,KF-P0005,Tensimeter Digital Forte,Vitamin & Suplemen,Tablet,CareOne,SUP086,67500,79500,0.18

Dataset: apotek
Shape: (100, 8)

  ApotekID KodeApotek             NamaApotek       Kota          Provinsi Wilayah          TipeCabang  StatusCabang
0   APT001  KF-BEK001    Kimia Farma Bekasi 1    Bekasi        Jawa Barat   Barat              Reguler        Aktif
1   APT002  KF-BAN002   Kimia Farma Bandung 2   Bandung        Jawa Barat   Barat  Klinik Terintegrasi        Aktif
2   APT003  KF-MAK003  Kimia Farma Makassar 3  Makassar  Sulawesi Selatan   timur  Klinik Terintegrasi        Aktif
3   APT004  KF-DEP004     Kimia Farma Depok 4     Depok        Jawa Barat   barat  Klinik Terintegrasi        Aktif
4   APT005  KF-BOG005     Kimia Farma Bogor 5     Bogor        Jawa Barat   Barat      Mall/Commercial        Aktif

Dataset: pelanggan
Shape: (150, 9)

,PelangganID,KodePelanggan,NamaPelanggan,JenisKelamin,Usia,KelompokUsia,Kota,Provinsi,TipePelanggan
0,PLG001,CUST00001,Sinta Hidayat,P,28,25-35,Surakarta,Jawa Tengah,Member
1,PLG002,CUST00002,Citra Santoso,P,25,25-35,Semarang,Jawa Tengah,Member
2,PLG003,CUST00003,Arif Lestari,L,66 thn,56+,Padang,Sumatera Barat,BPJS/Asuransi
3,PLG004,CUST00004,Doni Pangestu,L,55,46-55,Bogor,Jawa Barat,Corporate
4,PLG005,CUST00005,Fajar Ramadhan,L,68,56+,Balikpapan,Kalimantan Timur,Member

Dataset: karyawan
Shape: (122, 8)

  KaryawanID          NIK   NamaKaryawan JenisKelamin           Jabatan          Departemen ApotekID StatusKepegawaian
0     KRY001  KF202600001  Ilham Saputra            L               NaN        Administrasi   APT053            Magang
1     KRY002  KF202600002    Fikri Utami            L  Asisten Apoteker             Farmasi   APT027           Kontrak
2     KRY003  KF202600003  Ilham Hidayat            L             Kasir  Operasional Apotek   APT069             Tetap
3     kry004  KF202600004   Hendra Fauzi            L      Admin Cabang        Administrasi   APT078             Tetap
4     kry005  KF202600005   Bayu Azzahra            L      Admin Cabang        Administrasi   APT028            Magang

Dataset: supplier
Shape: (100, 6)

  SupplierID          NamaSupplier  KotaSupplier   ProvinsiSupplier WilayahSupplier     KategoriSupplier
0     SUP001   PT Herbal Nusantara     Yogyakarta     DI Yogyakarta          Tengah           Obat Bebas
1     SUP002  PT Sentosa Sejahtera         BEKASI        Jawa Barat           Barat  Perawatan Kesehatan
2     SUP003     PT Vita Indonesia       MAKASSAR  Sulawesi Selatan           Timur       Alat Kesehatan
3     SUP004   PT Medika Nusantara  Jakarta Timur       DKI Jakarta           Barat           Obat Bebas
4     SUP005       PT Sentosa Jaya     Balikpapan  Kalimantan Timur           Timur         Obat Generik

Dataset: penjualan
Shape: (1003, 14)

,ID_Faktur,tgl_trx,Kode_Barang,ID_Apotek,PelangganID,Kasir_ID,SupplierID,JumlahTerjual,Harga_Satuan,Diskon,TotalPenjualan,Keuntungan,MetodePembayaran,ChannelTransaksi
0,FKT00001,04-07-2026,PRD012,APT087,PLG146,KRY077,SUP054,2,15500,0.0,31000,7000,Kredit,Apotek Ritel Internal
1,FKT00002,01/04/2026,PRD030,APT004,PLG016,KRY071,SUP084,2,16500,1600.0,31400,8400,Kredit,Apotek Ritel Internal
2,FKT00003,05-08-2026,PRD007,APT054,PLG040,KRY079,SUP073,1,30500,0.0,30500,5500,QRIS,Apotek Ritel Internal
3,FKT00004,21/03/2026,PRD046,APT065,PLG017,KRY033,SUP085,3,41000,18400.0,104600,2600,QRIS,Apotek Ritel Internal
4,FKT00005,04/11/2026,PRD052,APT061,PLG080,KRY086,SUP006,4,23500,0.0,94000,18000,Tunai,Apotek Ritel Internal

In [5]:
# ============================================================
# CELL 4: DATA UNDERSTANDING
# ============================================================

for name, df in datasets.items():
    print("=" * 80)
    print(f"INFO DATASET: {name.upper()}")
    print("=" * 80)

    print("\nKolom:")
    print(df.columns.tolist())

    print("\nJumlah baris dan kolom:")
    print(df.shape)

    print("\nTipe data:")
    print(df.dtypes)

    print("\nMissing value:")
    print(df.isnull().sum())

    print("\nJumlah duplikasi:")
    print(df.duplicated().sum())

    print("\nPreview:")
    display(df.head())

================================================================================
INFO DATASET: PRODUK
================================================================================

Kolom:
['ProdukID', 'KodeProduk', ' Nama Produk ', 'KategoriProduk', 'JenisProduk', 'Brand', 'SupplierID', 'HargaModal', 'HargaSatuanDefault', 'MarginDefault']

Jumlah baris dan kolom:
(120, 10)

Tipe data:
ProdukID               object
KodeProduk             object
 Nama Produk           object
KategoriProduk         object
JenisProduk            object
Brand                  object
SupplierID             object
HargaModal              int64
HargaSatuanDefault      int64
MarginDefault         float64
dtype: object

Missing value:
ProdukID               0
KodeProduk             0
 Nama Produk           0
KategoriProduk        23
JenisProduk            0
Brand                  0
SupplierID             0
HargaModal             0
HargaSatuanDefault     0
MarginDefault          0
dtype: int64

Jumlah duplikasi:
0

Preview:

,ProdukID,KodeProduk,Nama Produk,KategoriProduk,JenisProduk,Brand,SupplierID,HargaModal,HargaSatuanDefault,MarginDefault
0,prd001,KF-P0001,Gel Nyeri Otot Forte,Obat Bebas,Tablet,Kimia Farma,SUP034,25500,32000,0.25
1,PRD002,KF-P0002,Termometer Digital,Obat Bebas,Salep,NaturaFit,SUP078,43000,51500,0.20
2,PRD003,KF-P0003,Gel Nyeri Otot Care,Obat Bebas,Salep,CareOne,SUP006,27000,32000,0.18
3,PRD004,KF-P0004,Termometer Digital Family,Obat Bebas,Sirup,AlkesPro,SUP043,11500,15000,0.30
4,PRD005,KF-P0005,Tensimeter Digital Forte,Vitamin & Suplemen,Tablet,CareOne,SUP086,67500,79500,0.18

================================================================================
INFO DATASET: APOTEK
================================================================================

Kolom:
['ApotekID', 'KodeApotek', ' NamaApotek ', 'Kota', 'Provinsi', 'Wilayah', ' TipeCabang ', 'StatusCabang']

Jumlah baris dan kolom:
(100, 8)

Tipe data:
ApotekID        object
KodeApotek      object
 NamaApotek     object
Kota            object
Provinsi        object
Wilayah         object
 TipeCabang     object
StatusCabang    object
dtype: object

Missing value:
ApotekID        0
KodeApotek      0
 NamaApotek     0
Kota            0
Provinsi        0
Wilayah         0
 TipeCabang     0
StatusCabang    0
dtype: int64

Jumlah duplikasi:
0

Preview:

  ApotekID KodeApotek             NamaApotek       Kota          Provinsi Wilayah          TipeCabang  StatusCabang
0   APT001  KF-BEK001    Kimia Farma Bekasi 1    Bekasi        Jawa Barat   Barat              Reguler        Aktif
1   APT002  KF-BAN002   Kimia Farma Bandung 2   Bandung        Jawa Barat   Barat  Klinik Terintegrasi        Aktif
2   APT003  KF-MAK003  Kimia Farma Makassar 3  Makassar  Sulawesi Selatan   timur  Klinik Terintegrasi        Aktif
3   APT004  KF-DEP004     Kimia Farma Depok 4     Depok        Jawa Barat   barat  Klinik Terintegrasi        Aktif
4   APT005  KF-BOG005     Kimia Farma Bogor 5     Bogor        Jawa Barat   Barat      Mall/Commercial        Aktif

================================================================================
INFO DATASET: PELANGGAN
================================================================================

Kolom:
['PelangganID', 'KodePelanggan', 'NamaPelanggan', 'JenisKelamin', 'Usia', 'KelompokUsia', 'Kota', 'Provinsi', 'TipePelanggan']

Jumlah baris dan kolom:
(150, 9)

Tipe data:
PelangganID      object
KodePelanggan    object
NamaPelanggan    object
JenisKelamin     object
Usia             object
KelompokUsia     object
Kota             object
Provinsi         object
TipePelanggan    object
dtype: object

Missing value:
PelangganID       0
KodePelanggan     0
NamaPelanggan     0
JenisKelamin     13
Usia             18
KelompokUsia      0
Kota              0
Provinsi          0
TipePelanggan     0
dtype: int64

Jumlah duplikasi:
0

Preview:

,PelangganID,KodePelanggan,NamaPelanggan,JenisKelamin,Usia,KelompokUsia,Kota,Provinsi,TipePelanggan
0,PLG001,CUST00001,Sinta Hidayat,P,28,25-35,Surakarta,Jawa Tengah,Member
1,PLG002,CUST00002,Citra Santoso,P,25,25-35,Semarang,Jawa Tengah,Member
2,PLG003,CUST00003,Arif Lestari,L,66 thn,56+,Padang,Sumatera Barat,BPJS/Asuransi
3,PLG004,CUST00004,Doni Pangestu,L,55,46-55,Bogor,Jawa Barat,Corporate
4,PLG005,CUST00005,Fajar Ramadhan,L,68,56+,Balikpapan,Kalimantan Timur,Member

================================================================================
INFO DATASET: KARYAWAN
================================================================================

Kolom:
['KaryawanID', 'NIK', 'NamaKaryawan', 'JenisKelamin', 'Jabatan', 'Departemen', 'ApotekID', 'StatusKepegawaian']

Jumlah baris dan kolom:
(122, 8)

Tipe data:
KaryawanID           object
NIK                  object
NamaKaryawan         object
JenisKelamin         object
Jabatan              object
Departemen           object
ApotekID             object
StatusKepegawaian    object
dtype: object

Missing value:
KaryawanID            0
NIK                   0
NamaKaryawan          0
JenisKelamin          0
Jabatan              14
Departemen            0
ApotekID              0
StatusKepegawaian     0
dtype: int64

Jumlah duplikasi:
2

Preview:

  KaryawanID          NIK   NamaKaryawan JenisKelamin           Jabatan          Departemen ApotekID StatusKepegawaian
0     KRY001  KF202600001  Ilham Saputra            L               NaN        Administrasi   APT053            Magang
1     KRY002  KF202600002    Fikri Utami            L  Asisten Apoteker             Farmasi   APT027           Kontrak
2     KRY003  KF202600003  Ilham Hidayat            L             Kasir  Operasional Apotek   APT069             Tetap
3     kry004  KF202600004   Hendra Fauzi            L      Admin Cabang        Administrasi   APT078             Tetap
4     kry005  KF202600005   Bayu Azzahra            L      Admin Cabang        Administrasi   APT028            Magang

================================================================================
INFO DATASET: SUPPLIER
================================================================================

Kolom:
['SupplierID', 'NamaSupplier', ' KotaSupplier ', 'ProvinsiSupplier', 'WilayahSupplier', 'KategoriSupplier']

Jumlah baris dan kolom:
(100, 6)

Tipe data:
SupplierID          object
NamaSupplier        object
 KotaSupplier       object
ProvinsiSupplier    object
WilayahSupplier     object
KategoriSupplier    object
dtype: object

Missing value:
SupplierID          0
NamaSupplier        0
 KotaSupplier       0
ProvinsiSupplier    0
WilayahSupplier     0
KategoriSupplier    0
dtype: int64

Jumlah duplikasi:
0

Preview:

  SupplierID          NamaSupplier  KotaSupplier   ProvinsiSupplier WilayahSupplier     KategoriSupplier
0     SUP001   PT Herbal Nusantara     Yogyakarta     DI Yogyakarta          Tengah           Obat Bebas
1     SUP002  PT Sentosa Sejahtera         BEKASI        Jawa Barat           Barat  Perawatan Kesehatan
2     SUP003     PT Vita Indonesia       MAKASSAR  Sulawesi Selatan           Timur       Alat Kesehatan
3     SUP004   PT Medika Nusantara  Jakarta Timur       DKI Jakarta           Barat           Obat Bebas
4     SUP005       PT Sentosa Jaya     Balikpapan  Kalimantan Timur           Timur         Obat Generik

================================================================================
INFO DATASET: PENJUALAN
================================================================================

Kolom:
['ID_Faktur ', 'tgl_trx', ' Kode_Barang ', ' ID_Apotek ', 'PelangganID', 'Kasir_ID', 'SupplierID', 'JumlahTerjual', 'Harga_Satuan', 'Diskon', 'TotalPenjualan', 'Keuntungan', 'MetodePembayaran', 'ChannelTransaksi']

Jumlah baris dan kolom:
(1003, 14)

Tipe data:
ID_Faktur            object
tgl_trx              object
 Kode_Barang         object
 ID_Apotek           object
PelangganID          object
Kasir_ID             object
SupplierID           object
JumlahTerjual         int64
Harga_Satuan          int64
Diskon              float64
TotalPenjualan        int64
Keuntungan            int64
MetodePembayaran     object
ChannelTransaksi     object
dtype: object

Missing value:
ID_Faktur            0
tgl_trx              0
 Kode_Barang         0
 ID_Apotek           0
PelangganID          0
Kasir_ID             0
SupplierID           0
JumlahTerjual        0
Harga_Satuan         0
Diskon              33
TotalPenjualan       0
Keuntungan           0
MetodePembayaran     0
ChannelTransaksi     0
dtype: int64

Jumlah duplikasi:
3

Preview:

,ID_Faktur,tgl_trx,Kode_Barang,ID_Apotek,PelangganID,Kasir_ID,SupplierID,JumlahTerjual,Harga_Satuan,Diskon,TotalPenjualan,Keuntungan,MetodePembayaran,ChannelTransaksi
0,FKT00001,04-07-2026,PRD012,APT087,PLG146,KRY077,SUP054,2,15500,0.0,31000,7000,Kredit,Apotek Ritel Internal
1,FKT00002,01/04/2026,PRD030,APT004,PLG016,KRY071,SUP084,2,16500,1600.0,31400,8400,Kredit,Apotek Ritel Internal
2,FKT00003,05-08-2026,PRD007,APT054,PLG040,KRY079,SUP073,1,30500,0.0,30500,5500,QRIS,Apotek Ritel Internal
3,FKT00004,21/03/2026,PRD046,APT065,PLG017,KRY033,SUP085,3,41000,18400.0,104600,2600,QRIS,Apotek Ritel Internal
4,FKT00005,04/11/2026,PRD052,APT061,PLG080,KRY086,SUP006,4,23500,0.0,94000,18000,Tunai,Apotek Ritel Internal

# **Transform**

In [6]:
# ============================================================
# CELL 5: STANDARDISASI NAMA KOLOM
# ============================================================

def clean_column_names(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )
    return df

produk = clean_column_names(produk)
apotek = clean_column_names(apotek)
pelanggan = clean_column_names(pelanggan)
karyawan = clean_column_names(karyawan)
supplier = clean_column_names(supplier)
penjualan = clean_column_names(penjualan)

print("[LOG] Menyelaraskan istilah nama kolom khusus tabel Penjualan & Produk...")

penjualan = penjualan.rename(columns={
    "ID_Faktur": "FakturID",
    "tgl_trx": "Tanggal",
    "Kode_Barang": "ProdukID",
    "ID_Apotek": "ApotekID",
    "Kasir_ID": "KaryawanID",
    "Harga_Satuan": "HargaSatuan"
})

produk = produk.rename(columns={
    "Nama_Produk": "NamaProduk"
})

datasets = {
    "produk": produk,
    "apotek": apotek,
    "pelanggan": pelanggan,
    "karyawan": karyawan,
    "supplier": supplier,
    "penjualan": penjualan
}

print("\n=== LAPORAN FIXING STRUKTUR KOLOM ===")
for name, df in datasets.items():
    print(f"✔️ Tabel {name:<10} : {df.columns.tolist()}")

print("\n[STATUS] Penamaan kolom telah distandardisasi dan siap divalidasi oleh CELL 6.")

[LOG] Menyelaraskan istilah nama kolom khusus tabel Penjualan & Produk...

=== LAPORAN FIXING STRUKTUR KOLOM ===
✔️ Tabel produk     : ['ProdukID', 'KodeProduk', 'NamaProduk', 'KategoriProduk', 'JenisProduk', 'Brand', 'SupplierID', 'HargaModal', 'HargaSatuanDefault', 'MarginDefault']
✔️ Tabel apotek     : ['ApotekID', 'KodeApotek', 'NamaApotek', 'Kota', 'Provinsi', 'Wilayah', 'TipeCabang', 'StatusCabang']
✔️ Tabel pelanggan  : ['PelangganID', 'KodePelanggan', 'NamaPelanggan', 'JenisKelamin', 'Usia', 'KelompokUsia', 'Kota', 'Provinsi', 'TipePelanggan']
✔️ Tabel karyawan   : ['KaryawanID', 'NIK', 'NamaKaryawan', 'JenisKelamin', 'Jabatan', 'Departemen', 'ApotekID', 'StatusKepegawaian']
✔️ Tabel supplier   : ['SupplierID', 'NamaSupplier', 'KotaSupplier', 'ProvinsiSupplier', 'WilayahSupplier', 'KategoriSupplier']
✔️ Tabel penjualan  : ['FakturID', 'Tanggal', 'ProdukID', 'ApotekID', 'PelangganID', 'KaryawanID', 'SupplierID', 'JumlahTerjual', 'HargaSatuan', 'Diskon', 'TotalPenjualan', 'Keuntungan', 'MetodePembayaran', 'ChannelTransaksi']

[STATUS] Penamaan kolom telah distandardisasi dan siap divalidasi oleh CELL 6.

In [7]:
# ============================================================
# CELL 6: VALIDASI KOLOM WAJIB
# ============================================================

required_columns = {
    "produk": ["ProdukID"],
    "apotek": ["ApotekID"],
    "pelanggan": ["PelangganID"],
    "karyawan": ["KaryawanID"],
    "supplier": ["SupplierID"],
    "penjualan": [
        "FakturID",
        "Tanggal",
        "ProdukID",
        "ApotekID",
        "PelangganID",
        "KaryawanID",
        "SupplierID",
        "JumlahTerjual",
        "HargaSatuan",
        "Diskon"
    ]
}

for dataset_name, columns in required_columns.items():
    df = datasets[dataset_name]
    missing_cols = [col for col in columns if col not in df.columns]

    if missing_cols:
        print(f"[ERROR] Dataset {dataset_name} kekurangan kolom: {missing_cols}")
    else:
        print(f"[OK] Dataset {dataset_name} memiliki semua kolom wajib.")

[OK] Dataset produk memiliki semua kolom wajib.
[OK] Dataset apotek memiliki semua kolom wajib.
[OK] Dataset pelanggan memiliki semua kolom wajib.
[OK] Dataset karyawan memiliki semua kolom wajib.
[OK] Dataset supplier memiliki semua kolom wajib.
[OK] Dataset penjualan memiliki semua kolom wajib.

In [8]:
# ============================================================
# CELL 7: DATA CLEANING DASAR
# ============================================================

def basic_cleaning(df):
    df = df.copy()

    # Hapus baris duplikat
    df = df.drop_duplicates()

    # Bersihkan spasi pada kolom bertipe string
    for col in df.select_dtypes(include=["object"]).columns:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace({"nan": np.nan, "None": np.nan, "": np.nan})

    return df

produk = basic_cleaning(produk)
apotek = basic_cleaning(apotek)
pelanggan = basic_cleaning(pelanggan)
karyawan = basic_cleaning(karyawan)
supplier = basic_cleaning(supplier)
penjualan = basic_cleaning(penjualan)

print("Cleaning dasar selesai.")

for name, df in {
    "produk": produk,
    "apotek": apotek,
    "pelanggan": pelanggan,
    "karyawan": karyawan,
    "supplier": supplier,
    "penjualan": penjualan
}.items():
    print(f"{name}: {df.shape}")

Cleaning dasar selesai.
produk: (120, 10)
apotek: (100, 8)
pelanggan: (150, 9)
karyawan: (120, 8)
supplier: (100, 6)
penjualan: (1000, 14)

In [9]:
# ============================================================
# CELL 8: PERBAIKAN TIPE DATA
# ============================================================

# Ubah tanggal transaksi ke format datetime
penjualan["Tanggal"] = pd.to_datetime(penjualan["Tanggal"], format='mixed', errors='coerce')

# Kolom numerik pada transaksi
numeric_cols = ["JumlahTerjual", "HargaSatuan", "Diskon"]

for col in numeric_cols:
    if col in penjualan.columns:
        penjualan[col] = pd.to_numeric(penjualan[col], errors="coerce")

# Jika ada usia pelanggan, ubah ke numerik
if "Usia" in pelanggan.columns:
    pelanggan["Usia"] = pd.to_numeric(pelanggan["Usia"], errors="coerce")

print("Tipe data berhasil diperbaiki.")

print("\nTipe data penjualan:")
print(penjualan.dtypes)

print("\nPreview penjualan:")
display(penjualan.head())

Tipe data berhasil diperbaiki.

Tipe data penjualan:
FakturID                    object
Tanggal             datetime64[ns]
ProdukID                    object
ApotekID                    object
PelangganID                 object
KaryawanID                  object
SupplierID                  object
JumlahTerjual                int64
HargaSatuan                  int64
Diskon                     float64
TotalPenjualan               int64
Keuntungan                   int64
MetodePembayaran            object
ChannelTransaksi            object
dtype: object

Preview penjualan:

,FakturID,Tanggal,ProdukID,ApotekID,PelangganID,KaryawanID,SupplierID,JumlahTerjual,HargaSatuan,Diskon,TotalPenjualan,Keuntungan,MetodePembayaran,ChannelTransaksi
0,FKT00001,2026-04-07,PRD012,APT087,PLG146,KRY077,SUP054,2,15500,0.0,31000,7000,Kredit,Apotek Ritel Internal
1,FKT00002,2026-01-04,PRD030,APT004,PLG016,KRY071,SUP084,2,16500,1600.0,31400,8400,Kredit,Apotek Ritel Internal
2,FKT00003,2026-05-08,PRD007,APT054,PLG040,KRY079,SUP073,1,30500,0.0,30500,5500,QRIS,Apotek Ritel Internal
3,FKT00004,2026-03-21,PRD046,APT065,PLG017,KRY033,SUP085,3,41000,18400.0,104600,2600,QRIS,Apotek Ritel Internal
4,FKT00005,2026-04-11,PRD052,APT061,PLG080,KRY086,SUP006,4,23500,0.0,94000,18000,Tunai,Apotek Ritel Internal

In [10]:
# ============================================================
# CELL 9: HANDLE MISSING VALUE
# ============================================================

# Hapus transaksi yang tidak punya ID penting atau tanggal
important_transaction_cols = ["FakturID", "Tanggal", "ProdukID", "ApotekID", "PelangganID", "KaryawanID", "SupplierID"]
existing_important_cols = [col for col in important_transaction_cols if col in penjualan.columns]

# Rekam statistik data bolong awal sebelum pengisian
before_rows = len(penjualan)

# Drop baris transaksi yang tidak memiliki kunci relasi utama
penjualan = penjualan.dropna(subset=existing_important_cols).copy()
after_rows = len(penjualan)

# Isi missing value finansial numerik transaksi dengan 0
numeric_sales_cols = ["JumlahTerjual", "HargaSatuan", "Diskon", "TotalPenjualan", "Keuntungan"]
filled_numeric_count = 0
for col in numeric_sales_cols:
    if col in penjualan.columns:
        filled_numeric_count += penjualan[col].isnull().sum()
        penjualan[col] = penjualan[col].fillna(0)

# Isi missing value teks dimensi dengan label 'Unknown'
dimension_tables = {"Produk": produk, "Apotek": apotek, "Pelanggan": pelanggan, "Karyawan": karyawan, "Supplier": supplier}
filled_text_count = 0
for name, df_dim in dimension_tables.items():
    for col in df_dim.select_dtypes(include=["object"]).columns:
        filled_text_count += df_dim[col].isnull().sum()
        df_dim[col] = df_dim[col].fillna("Unknown")

# Isi Usia Pelanggan dengan Median
if "Usia" in pelanggan.columns:
    missing_usia_count = pelanggan["Usia"].isnull().sum()
    median_value = pelanggan["Usia"].median()
    pelanggan["Usia"] = pelanggan["Usia"].fillna(median_value)

# Cetak ringkasan log transformasi missing value
print("=== LAPORAN INTEGRITAS DATA MISSING VALUE ===")
print(f"1. Menghapus {before_rows - after_rows} baris transaksi karena kolom kunci utama/tanggal bernilai Kosong.")
print(f"2. Mengamankan {filled_numeric_count} nilai finansial kosong pada data transaksi dengan angka 0.")
print(f"3. Mengisi {filled_text_count} data teks kosong di seluruh tabel Dimensi dengan kategori 'Unknown'.")
if "Usia" in pelanggan.columns:
    print(f"4. Melakukan imputasi pada {missing_usia_count} baris data Usia Pelanggan menggunakan nilai Median ({median_value} tahun).")

print("\n[STATUS] Hasil Akhir Pengecekan Kerusakan Data (Harus Berjumlah 0):")
for name, df_dim in dimension_tables.items():
    print(f"  - Total Missing Value di {name:<10}: {df_dim.isnull().sum().sum()} baris")
print(f"  - Total Missing Value di Penjualan : {penjualan.isnull().sum().sum()} baris")

=== LAPORAN INTEGRITAS DATA MISSING VALUE ===
1. Menghapus 0 baris transaksi karena kolom kunci utama/tanggal bernilai Kosong.
2. Mengamankan 33 nilai finansial kosong pada data transaksi dengan angka 0.
3. Mengisi 50 data teks kosong di seluruh tabel Dimensi dengan kategori 'Unknown'.
4. Melakukan imputasi pada 65 baris data Usia Pelanggan menggunakan nilai Median (45.0 tahun).

[STATUS] Hasil Akhir Pengecekan Kerusakan Data (Harus Berjumlah 0):
  - Total Missing Value di Produk    : 0 baris
  - Total Missing Value di Apotek    : 0 baris
  - Total Missing Value di Pelanggan : 0 baris
  - Total Missing Value di Karyawan  : 0 baris
  - Total Missing Value di Supplier  : 0 baris
  - Total Missing Value di Penjualan : 0 baris

In [11]:
# ============================================================
# CELL 10: VALIDASI RELASI FOREIGN KEY
# ============================================================

def validate_foreign_key(fact_df, dim_df, fk_col, dim_key_col, dim_name):
    fact_keys = set(fact_df[fk_col].dropna().unique())
    dim_keys = set(dim_df[dim_key_col].dropna().unique())

    invalid_keys = fact_keys - dim_keys

    print(f"============================================================")
    print(f"🔗 VALIDASI RELASI: {fk_col} ➔ {dim_name}.{dim_key_col}")
    print(f"============================================================")
    print(f"  [KUNCI UNIK DI FACT]    : {len(fact_keys)} entitas")
    print(f"  [KUNCI UNIK DI DIMENSI] : {len(dim_keys)} entitas")
    print(f"  [KUNCI TIDAK VALID]     : {len(invalid_keys)} entitas")

    if len(invalid_keys) > 0:
        print("Contoh key tidak valid:", list(invalid_keys)[:10])
    else:
        print("[OK] Semua key valid.")

    return invalid_keys

invalid_produk = validate_foreign_key(penjualan, produk, "ProdukID", "ProdukID", "Dim_Produk")
invalid_apotek = validate_foreign_key(penjualan, apotek, "ApotekID", "ApotekID", "Dim_Apotek")
invalid_pelanggan = validate_foreign_key(penjualan, pelanggan, "PelangganID", "PelangganID", "Dim_Pelanggan")
invalid_karyawan = validate_foreign_key(penjualan, karyawan, "KaryawanID", "KaryawanID", "Dim_Karyawan")
invalid_supplier = validate_foreign_key(penjualan, supplier, "SupplierID", "SupplierID", "Dim_Supplier")

============================================================
🔗 VALIDASI RELASI: ProdukID ➔ Dim_Produk.ProdukID
============================================================
  [KUNCI UNIK DI FACT]    : 120 entitas
  [KUNCI UNIK DI DIMENSI] : 120 entitas
  [KUNCI TIDAK VALID]     : 34 entitas
Contoh key tidak valid: ['PRD098', 'PRD083', 'PRD001', 'PRD029', 'PRD111', 'PRD057', 'PRD031', 'PRD115', 'PRD046', 'PRD102']
============================================================
🔗 VALIDASI RELASI: ApotekID ➔ Dim_Apotek.ApotekID
============================================================
  [KUNCI UNIK DI FACT]    : 100 entitas
  [KUNCI UNIK DI DIMENSI] : 100 entitas
  [KUNCI TIDAK VALID]     : 0 entitas
[OK] Semua key valid.
============================================================
🔗 VALIDASI RELASI: PelangganID ➔ Dim_Pelanggan.PelangganID
============================================================
  [KUNCI UNIK DI FACT]    : 150 entitas
  [KUNCI UNIK DI DIMENSI] : 150 entitas
  [KUNCI TIDAK VALID]     : 0 entitas
[OK] Semua key valid.
============================================================
🔗 VALIDASI RELASI: KaryawanID ➔ Dim_Karyawan.KaryawanID
============================================================
  [KUNCI UNIK DI FACT]    : 120 entitas
  [KUNCI UNIK DI DIMENSI] : 120 entitas
  [KUNCI TIDAK VALID]     : 32 entitas
Contoh key tidak valid: ['KRY014', 'KRY039', 'KRY068', 'KRY056', 'KRY078', 'KRY005', 'KRY017', 'KRY118', 'KRY089', 'KRY091']
============================================================
🔗 VALIDASI RELASI: SupplierID ➔ Dim_Supplier.SupplierID
============================================================
  [KUNCI UNIK DI FACT]    : 71 entitas
  [KUNCI UNIK DI DIMENSI] : 100 entitas
  [KUNCI TIDAK VALID]     : 0 entitas
[OK] Semua key valid.

In [12]:
# ============================================================
# CELL 11: FILTER TRANSAKSI YANG VALID
# ============================================================
before_rows = len(penjualan)
print(f"[LOG AWAL CELL 11] Jumlah transaksi masuk: {before_rows} baris")

# --- KODE PENANGANAN UPPERCASE / LOWERCASE ---
# Mengubah semua ID di tabel transaksi (fakta) menjadi huruf besar
for col in ["ProdukID", "ApotekID", "PelangganID", "KaryawanID", "SupplierID"]:
    if col in penjualan.columns:
        penjualan[col] = penjualan[col].astype(str).str.strip().str.upper()

# Mengubah semua ID di tabel master dimensi menjadi huruf besar agar sinkron
produk["ProdukID"] = produk["ProdukID"].astype(str).str.strip().str.upper()
apotek["ApotekID"] = apotek["ApotekID"].astype(str).str.strip().str.upper()
pelanggan["PelangganID"] = pelanggan["PelangganID"].astype(str).str.strip().str.upper()
karyawan["KaryawanID"] = karyawan["KaryawanID"].astype(str).str.strip().str.upper()
supplier["SupplierID"] = supplier["SupplierID"].astype(str).str.strip().str.upper()
# -----------------------------------------------------

# Daftar pasangan kolom kunci di tabel fakta dan dataframe dimensi pasangannya
dim_relations = {
    "ProdukID": produk,
    "ApotekID": apotek,
    "PelangganID": pelanggan,
    "KaryawanID": karyawan,
    "SupplierID": supplier
}

# Looping untuk mengecek kecocokan data di setiap foreign key
for fk_col, dim_df in dim_relations.items():
    if fk_col in penjualan.columns:
        # Ambil semua ID unik yang valid dari master data dimensi
        valid_ids = set(dim_df[fk_col].astype(str).unique())

        # Cari baris transaksi yang ID-nya TIDAK ADA di master data dimensi
        invalid_mask = ~penjualan[fk_col].astype(str).isin(valid_ids)
        invalid_count = invalid_mask.sum()

        if invalid_count > 0:
            # JANGAN DI-DROP! Ubah nilainya menjadi 'Unknown'
            penjualan.loc[invalid_mask, fk_col] = "Unknown"
            print(f"  ✔️ Berhasil menyelamatkan {invalid_count} baris transaksi pada kolom '{fk_col}' (diubah menjadi 'Unknown').")

after_rows = len(penjualan)

print(f"\nJumlah transaksi sebelum filter: {before_rows}")
print(f"Jumlah transaksi setelah filter (Unknown Member): {after_rows}")
print(f"Jumlah transaksi terhapus: {before_rows - after_rows} baris (0% Data Bocor!)")

[LOG AWAL CELL 11] Jumlah transaksi masuk: 1000 baris

Jumlah transaksi sebelum filter: 1000
Jumlah transaksi setelah filter (Unknown Member): 1000
Jumlah transaksi terhapus: 0 baris (0% Data Bocor!)

In [13]:
# ============================================================
# CELL 12: MEMBUAT DIM_WAKTU
# ============================================================

dim_waktu = penjualan[["Tanggal"]].drop_duplicates().copy()

dim_waktu["WaktuID"] = dim_waktu["Tanggal"].dt.strftime("%Y%m%d").astype(int)
dim_waktu["Tanggal"] = dim_waktu["Tanggal"].dt.date
dim_waktu["Hari"] = pd.to_datetime(dim_waktu["Tanggal"]).dt.day_name()
dim_waktu["Bulan"] = pd.to_datetime(dim_waktu["Tanggal"]).dt.month_name()
dim_waktu["NomorBulan"] = pd.to_datetime(dim_waktu["Tanggal"]).dt.month
dim_waktu["Kuartal"] = "Q" + pd.to_datetime(dim_waktu["Tanggal"]).dt.quarter.astype(str)
dim_waktu["Tahun"] = pd.to_datetime(dim_waktu["Tanggal"]).dt.year

# Urutkan kolom
dim_waktu = dim_waktu[
    ["WaktuID", "Tanggal", "Hari", "Bulan", "NomorBulan", "Kuartal", "Tahun"]
].sort_values("WaktuID").reset_index(drop=True)

display(dim_waktu.head())
print("Jumlah baris Dim_Waktu:", len(dim_waktu))

    WaktuID     Tanggal       Hari    Bulan  NomorBulan Kuartal  Tahun
0  20260104  2026-01-04     Sunday  January           1      Q1   2026
1  20260105  2026-01-05     Monday  January           1      Q1   2026
2  20260106  2026-01-06    Tuesday  January           1      Q1   2026
3  20260107  2026-01-07  Wednesday  January           1      Q1   2026
4  20260108  2026-01-08   Thursday  January           1      Q1   2026

Jumlah baris Dim_Waktu: 339

In [14]:
# ============================================================
# CELL 13: MEMBUAT DIM_PRODUK
# ============================================================

dim_produk = produk.copy()

# Hapus duplikasi berdasarkan ProdukID
dim_produk = dim_produk.drop_duplicates(subset=["ProdukID"])

# Pilih kolom yang relevan jika tersedia
produk_cols = [
    "ProdukID",
    "KodeProduk",
    "NamaProduk",
    "KategoriProduk",
    "JenisProduk",
    "Brand",
    "SupplierID",
    "HargaModal"
]

available_produk_cols = [col for col in produk_cols if col in dim_produk.columns]
dim_produk = dim_produk[available_produk_cols].copy()

display(dim_produk.head())
print("Jumlah baris Dim_Produk:", len(dim_produk))

  ProdukID KodeProduk                 NamaProduk      KategoriProduk JenisProduk        Brand SupplierID  HargaModal
0   PRD001   KF-P0001       Gel Nyeri Otot Forte          Obat Bebas      Tablet  Kimia Farma     SUP034       25500
1   PRD002   KF-P0002         Termometer Digital          Obat Bebas       Salep    NaturaFit     SUP078       43000
2   PRD003   KF-P0003        Gel Nyeri Otot Care          Obat Bebas       Salep      CareOne     SUP006       27000
3   PRD004   KF-P0004  Termometer Digital Family          Obat Bebas       Sirup     AlkesPro     SUP043       11500
4   PRD005   KF-P0005   Tensimeter Digital Forte  Vitamin & Suplemen      Tablet      CareOne     SUP086       67500

Jumlah baris Dim_Produk: 120

In [15]:
# ============================================================
# CELL 14: MEMBUAT DIM_APOTEK
# ============================================================

dim_apotek = apotek.copy()
dim_apotek = dim_apotek.drop_duplicates(subset=["ApotekID"])

apotek_cols = [
    "ApotekID",
    "KodeApotek",
    "NamaApotek",
    "Kota",
    "Provinsi",
    "Wilayah",
    "TipeCabang"
]

available_apotek_cols = [col for col in apotek_cols if col in dim_apotek.columns]
dim_apotek = dim_apotek[available_apotek_cols].copy()

display(dim_apotek.head())
print("Jumlah baris Dim_Apotek:", len(dim_apotek))

  ApotekID KodeApotek              NamaApotek      Kota          Provinsi Wilayah           TipeCabang
0   APT001  KF-BEK001    Kimia Farma Bekasi 1    Bekasi        Jawa Barat   Barat              Reguler
1   APT002  KF-BAN002   Kimia Farma Bandung 2   Bandung        Jawa Barat   Barat  Klinik Terintegrasi
2   APT003  KF-MAK003  Kimia Farma Makassar 3  Makassar  Sulawesi Selatan   timur  Klinik Terintegrasi
3   APT004  KF-DEP004     Kimia Farma Depok 4     Depok        Jawa Barat   barat  Klinik Terintegrasi
4   APT005  KF-BOG005     Kimia Farma Bogor 5     Bogor        Jawa Barat   Barat      Mall/Commercial

Jumlah baris Dim_Apotek: 100

In [16]:
# ============================================================
# CELL 15: MEMBUAT DIM_PELANGGAN
# ============================================================

dim_pelanggan = pelanggan.copy()
dim_pelanggan = dim_pelanggan.drop_duplicates(subset=["PelangganID"])

# Tambahkan kelompok usia jika kolom Usia tersedia
if "Usia" in dim_pelanggan.columns:
    bins = [0, 17, 25, 35, 45, 55, 100]
    labels = ["<18", "18-25", "26-35", "36-45", "46-55", ">55"]
    dim_pelanggan["KelompokUsia"] = pd.cut(
        dim_pelanggan["Usia"],
        bins=bins,
        labels=labels,
        right=True
    )

pelanggan_cols = [
    "PelangganID",
    "KodePelanggan",
    "NamaPelanggan",
    "JenisKelamin",
    "Usia",
    "KelompokUsia",
    "Kota",
    "Provinsi",
    "TipePelanggan"
]

available_pelanggan_cols = [col for col in pelanggan_cols if col in dim_pelanggan.columns]
dim_pelanggan = dim_pelanggan[available_pelanggan_cols].copy()

display(dim_pelanggan.head())
print("Jumlah baris Dim_Pelanggan:", len(dim_pelanggan))

,PelangganID,KodePelanggan,NamaPelanggan,JenisKelamin,Usia,KelompokUsia,Kota,Provinsi,TipePelanggan
0,PLG001,CUST00001,Sinta Hidayat,P,28.0,26-35,Surakarta,Jawa Tengah,Member
1,PLG002,CUST00002,Citra Santoso,P,25.0,18-25,Semarang,Jawa Tengah,Member
2,PLG003,CUST00003,Arif Lestari,L,45.0,36-45,Padang,Sumatera Barat,BPJS/Asuransi
3,PLG004,CUST00004,Doni Pangestu,L,55.0,46-55,Bogor,Jawa Barat,Corporate
4,PLG005,CUST00005,Fajar Ramadhan,L,68.0,>55,Balikpapan,Kalimantan Timur,Member

Jumlah baris Dim_Pelanggan: 150

In [17]:
# ============================================================
# CELL 16: MEMBUAT DIM_KARYAWAN
# ============================================================

dim_karyawan = karyawan.copy()
dim_karyawan = dim_karyawan.drop_duplicates(subset=["KaryawanID"])

karyawan_cols = [
    "KaryawanID",
    "NIK",
    "NamaKaryawan",
    "Jabatan",
    "Departemen",
    "StatusKepegawaian",
    "ApotekID"
]

available_karyawan_cols = [col for col in karyawan_cols if col in dim_karyawan.columns]
dim_karyawan = dim_karyawan[available_karyawan_cols].copy()

display(dim_karyawan.head())
print("Jumlah baris Dim_Karyawan:", len(dim_karyawan))

  KaryawanID          NIK   NamaKaryawan           Jabatan          Departemen StatusKepegawaian ApotekID
0     KRY001  KF202600001  Ilham Saputra           Unknown        Administrasi            Magang   APT053
1     KRY002  KF202600002    Fikri Utami  Asisten Apoteker             Farmasi           Kontrak   APT027
2     KRY003  KF202600003  Ilham Hidayat             Kasir  Operasional Apotek             Tetap   APT069
3     KRY004  KF202600004   Hendra Fauzi      Admin Cabang        Administrasi             Tetap   APT078
4     KRY005  KF202600005   Bayu Azzahra      Admin Cabang        Administrasi            Magang   APT028

Jumlah baris Dim_Karyawan: 120

In [18]:
# ============================================================
# CELL 17: MEMBUAT DIM_SUPPLIER
# ============================================================

dim_supplier = supplier.copy()
dim_supplier = dim_supplier.drop_duplicates(subset=["SupplierID"])

supplier_cols = [
    "SupplierID",
    "NamaSupplier",
    "KotaSupplier"
]

available_supplier_cols = [col for col in supplier_cols if col in dim_supplier.columns]
dim_supplier = dim_supplier[available_supplier_cols].copy()

display(dim_supplier.head())
print("Jumlah baris Dim_Supplier:", len(dim_supplier))

  SupplierID          NamaSupplier   KotaSupplier
0     SUP001   PT Herbal Nusantara     Yogyakarta
1     SUP002  PT Sentosa Sejahtera         BEKASI
2     SUP003     PT Vita Indonesia       MAKASSAR
3     SUP004   PT Medika Nusantara  Jakarta Timur
4     SUP005       PT Sentosa Jaya     Balikpapan

Jumlah baris Dim_Supplier: 100

In [19]:
# ============================================================
# CELL 18: MEMBUAT FACT_PENJUALAN
# ============================================================

print(f"[LOG AWAL] Jumlah transaksi masuk: {len(penjualan)} baris")

# 1. Salin data dasar dari dataframe penjualan hasil cleaning
fact_penjualan = penjualan.copy()

# 2. Buat WaktuID dari tanggal transaksi (Gunakan fillna untuk mengamankan data kosong jika ada)
fact_penjualan["WaktuID"] = fact_penjualan["Tanggal"].dt.strftime("%Y%m%d")
# Jika ada WaktuID yang kosong karena anomali, isi dengan format tanggal default aman
fact_penjualan["WaktuID"] = fact_penjualan["WaktuID"].fillna("19700101").astype(int)

# 3. Hitung TotalPenjualan jika belum ada/perlu dihitung ulang
if "TotalPenjualan" not in fact_penjualan.columns or fact_penjualan["TotalPenjualan"].isnull().all():
    fact_penjualan["TotalPenjualan"] = (
        fact_penjualan["JumlahTerjual"] * fact_penjualan["HargaSatuan"]
    ) - fact_penjualan["Diskon"].fillna(0)

# Pastikan total penjualan tidak negatif akibat diskon besar
fact_penjualan["TotalPenjualan"] = fact_penjualan["TotalPenjualan"].clip(lower=0)

# 4. Hitung Keuntungan menggunakan HargaModal dari tabel dimensi
if "HargaModal" in dim_produk.columns:
    # Amankan dengan how='left' agar transaksi tidak hilang meskipun ProdukID-nya aneh
    fact_penjualan = fact_penjualan.merge(
        dim_produk[["ProdukID", "HargaModal"]],
        on="ProdukID",
        how="left"
    )

    fact_penjualan["HargaModal"] = pd.to_numeric(fact_penjualan["HargaModal"], errors="coerce").fillna(0)
    fact_penjualan["TotalModal"] = fact_penjualan["JumlahTerjual"] * fact_penjualan["HargaModal"]
    fact_penjualan["Keuntungan"] = fact_penjualan["TotalPenjualan"] - fact_penjualan["TotalModal"]
else:
    # Jika tidak ada HargaModal di tabel dimensi, gunakan margin simulasi 25%
    fact_penjualan["Keuntungan"] = fact_penjualan["TotalPenjualan"] * 0.25

# 5. SINKRONISASI INNER VS LEFT RELASI DIMENSI (Langkah Penyelamatan 1000 Baris)
# Menggunakan penanganan 'Unknown' agar foreign key di database PostgreSQL (Supabase) nanti tidak crash
dim_relations = {
    "ProdukID": dim_produk,
    "ApotekID": dim_apotek,
    "PelangganID": dim_pelanggan,
    "KaryawanID": dim_karyawan,
    "SupplierID": dim_supplier
}

print("[LOG] Memvalidasi kecocokan ID transaksi dengan Tabel Dimensi...")
for fk_col, dim_df in dim_relations.items():
    if fk_col in fact_penjualan.columns:
        valid_ids = set(dim_df[fk_col].astype(str).unique())
        # Cek baris transaksi yang ID-nya ga ada di master data dimensi
        invalid_mask = ~fact_penjualan[fk_col].astype(str).isin(valid_ids)
        invalid_count = invalid_mask.sum()

        if invalid_count > 0:
            fact_penjualan.loc[invalid_mask, fk_col] = "Unknown"
            print(f"  ⚠️ Mengamankan {invalid_count} baris transaksi pada '{fk_col}' dengan label 'Unknown' (Gara-gara ID ga match).")

# 6. Filter Kolom yang Resmi Masuk ke Tabel Fakta
fact_cols = [
    "FakturID",
    "WaktuID",
    "ProdukID",
    "ApotekID",
    "PelangganID",
    "KaryawanID",
    "SupplierID",
    "JumlahTerjual",
    "HargaSatuan",
    "Diskon",
    "TotalPenjualan",
    "Keuntungan"
]

available_fact_cols = [col for col in fact_cols if col in fact_penjualan.columns]
fact_penjualan = fact_penjualan[available_fact_cols].copy()

# 7. Tampilkan Preview Akhir
print("\n=== PREVIEW TABEL FAKTA PENJUALAN ===")
display(fact_penjualan.head())
print("Jumlah baris Akhir Fact_Penjualan:", len(fact_penjualan))

[LOG AWAL] Jumlah transaksi masuk: 1000 baris
[LOG] Memvalidasi kecocokan ID transaksi dengan Tabel Dimensi...

=== PREVIEW TABEL FAKTA PENJUALAN ===

,FakturID,WaktuID,ProdukID,ApotekID,PelangganID,KaryawanID,SupplierID,JumlahTerjual,HargaSatuan,Diskon,TotalPenjualan,Keuntungan
0,FKT00001,20260407,PRD012,APT087,PLG146,KRY077,SUP054,2,15500,0.0,31000,7000
1,FKT00002,20260104,PRD030,APT004,PLG016,KRY071,SUP084,2,16500,1600.0,31400,8400
2,FKT00003,20260508,PRD007,APT054,PLG040,KRY079,SUP073,1,30500,0.0,30500,5500
3,FKT00004,20260321,PRD046,APT065,PLG017,KRY033,SUP085,3,41000,18400.0,104600,2600
4,FKT00005,20260411,PRD052,APT061,PLG080,KRY086,SUP006,4,23500,0.0,94000,18000

Jumlah baris Akhir Fact_Penjualan: 1000

In [20]:
# ============================================================
# CELL 19: VALIDASI STAR SCHEMA
# ============================================================

print("Validasi jumlah data:")
print("Dim_Produk     :", dim_produk.shape)
print("Dim_Apotek     :", dim_apotek.shape)
print("Dim_Pelanggan  :", dim_pelanggan.shape)
print("Dim_Karyawan   :", dim_karyawan.shape)
print("Dim_Supplier   :", dim_supplier.shape)
print("Dim_Waktu      :", dim_waktu.shape)
print("Fact_Penjualan :", fact_penjualan.shape)

print("\nValidasi foreign key pada Fact_Penjualan:")

validate_foreign_key(fact_penjualan, dim_produk, "ProdukID", "ProdukID", "Dim_Produk")
validate_foreign_key(fact_penjualan, dim_apotek, "ApotekID", "ApotekID", "Dim_Apotek")
validate_foreign_key(fact_penjualan, dim_pelanggan, "PelangganID", "PelangganID", "Dim_Pelanggan")
validate_foreign_key(fact_penjualan, dim_karyawan, "KaryawanID", "KaryawanID", "Dim_Karyawan")
validate_foreign_key(fact_penjualan, dim_supplier, "SupplierID", "SupplierID", "Dim_Supplier")
validate_foreign_key(fact_penjualan, dim_waktu, "WaktuID", "WaktuID", "Dim_Waktu")

Validasi jumlah data:
Dim_Produk     : (120, 8)
Dim_Apotek     : (100, 7)
Dim_Pelanggan  : (150, 9)
Dim_Karyawan   : (120, 7)
Dim_Supplier   : (100, 3)
Dim_Waktu      : (339, 7)
Fact_Penjualan : (1000, 12)

Validasi foreign key pada Fact_Penjualan:
============================================================
🔗 VALIDASI RELASI: ProdukID ➔ Dim_Produk.ProdukID
============================================================
  [KUNCI UNIK DI FACT]    : 120 entitas
  [KUNCI UNIK DI DIMENSI] : 120 entitas
  [KUNCI TIDAK VALID]     : 0 entitas
[OK] Semua key valid.
============================================================
🔗 VALIDASI RELASI: ApotekID ➔ Dim_Apotek.ApotekID
============================================================
  [KUNCI UNIK DI FACT]    : 100 entitas
  [KUNCI UNIK DI DIMENSI] : 100 entitas
  [KUNCI TIDAK VALID]     : 0 entitas
[OK] Semua key valid.
============================================================
🔗 VALIDASI RELASI: PelangganID ➔ Dim_Pelanggan.PelangganID
============================================================
  [KUNCI UNIK DI FACT]    : 150 entitas
  [KUNCI UNIK DI DIMENSI] : 150 entitas
  [KUNCI TIDAK VALID]     : 0 entitas
[OK] Semua key valid.
============================================================
🔗 VALIDASI RELASI: KaryawanID ➔ Dim_Karyawan.KaryawanID
============================================================
  [KUNCI UNIK DI FACT]    : 120 entitas
  [KUNCI UNIK DI DIMENSI] : 120 entitas
  [KUNCI TIDAK VALID]     : 0 entitas
[OK] Semua key valid.
============================================================
🔗 VALIDASI RELASI: SupplierID ➔ Dim_Supplier.SupplierID
============================================================
  [KUNCI UNIK DI FACT]    : 71 entitas
  [KUNCI UNIK DI DIMENSI] : 100 entitas
  [KUNCI TIDAK VALID]     : 0 entitas
[OK] Semua key valid.
============================================================
🔗 VALIDASI RELASI: WaktuID ➔ Dim_Waktu.WaktuID
============================================================
  [KUNCI UNIK DI FACT]    : 339 entitas
  [KUNCI UNIK DI DIMENSI] : 339 entitas
  [KUNCI TIDAK VALID]     : 0 entitas
[OK] Semua key valid.

set()

In [21]:
import pandas as pd
import numpy as np
import os

# ============================================================
# CELL 20: PREVIEW DATA ANALITIK HASIL JOIN
# ============================================================

analyical_df = fact_penjualan.copy()

analyical_df = analyical_df.merge(dim_produk, on="ProdukID", how="left", suffixes=('', '_Produk'))
analyical_df = analyical_df.merge(dim_apotek, on="ApotekID", how="left")
analyical_df = analyical_df.merge(dim_pelanggan, on="PelangganID", how="left", suffixes=("", "_Pelanggan"))
analyical_df = analyical_df.merge(dim_karyawan, on="KaryawanID", how="left", suffixes=("", "_Karyawan"))
analyical_df = analyical_df.merge(dim_supplier, on="SupplierID", how="left")
analyical_df = analyical_df.merge(dim_waktu, on="WaktuID", how="left")

print("Shape data analitik:", analyical_df.shape)
display(analyical_df.head())

Shape data analitik: (1000, 47)

,FakturID,WaktuID,ProdukID,ApotekID,PelangganID,KaryawanID,SupplierID,JumlahTerjual,HargaSatuan,Diskon,TotalPenjualan,Keuntungan,KodeProduk,NamaProduk,KategoriProduk,JenisProduk,Brand,SupplierID_Produk,HargaModal,KodeApotek,NamaApotek,Kota,Provinsi,Wilayah,TipeCabang,KodePelanggan,NamaPelanggan,JenisKelamin,Usia,KelompokUsia,Kota_Pelanggan,Provinsi_Pelanggan,TipePelanggan,NIK,NamaKaryawan,Jabatan,Departemen,StatusKepegawaian,ApotekID_Karyawan,NamaSupplier,KotaSupplier,Tanggal,Hari,Bulan,NomorBulan,Kuartal,Tahun
0,FKT00001,20260407,PRD012,APT087,PLG146,KRY077,SUP054,2,15500,0.0,31000,7000,KF-P0012,Multivitamin Anak Family,Obat Bebas,Tablet,AlkesPro,SUP054,12000,KF-JAK087,Kimia Farma Jakarta Selatan 87,Jakarta Selatan,DKI Jakarta,barat,Mall/Commercial,CUST00146,Kevin Utami,L,45.0,36-45,Denpasar,Bali,Member,KF202600077,Gita Azzahra,Kasir,Operasional Apotek,Tetap,APT087,PT Indo Farma,DENPASAR,2026-04-07,Tuesday,April,4,Q2,2026
1,FKT00002,20260104,PRD030,APT004,PLG016,KRY071,SUP084,2,16500,1600.0,31400,8400,KF-P0030,Multivitamin Anak,Obat Bebas,Kapsul,Kimia Farma,SUP084,11500,KF-DEP004,Kimia Farma Depok 4,Depok,Jawa Barat,barat,Klinik Terintegrasi,CUST00016,Doni Lestari,L,67.0,>55,Surabaya,Jawa Timur,Member,KF202600071,Fajar Amelia,Supervisor Cabang,Operasional Apotek,Tetap,APT004,PT Mitra Sejahtera,yogyakarta,2026-01-04,Sunday,January,1,Q1,2026
2,FKT00003,20260508,PRD007,APT054,PLG040,KRY079,SUP073,1,30500,0.0,30500,5500,KF-P0007,Plester Luka,Unknown,Spray,HerbaNusa,SUP073,25000,KF-BOG054,Kimia Farma Bogor 54,Bogor,Jawa Barat,barat,Klinik Terintegrasi,CUST00040,Wulan Saputra,P,56.0,>55,Malang,Jawa Timur,Corporate,KF202600079,Maya Oktavia,Supervisor Cabang,Operasional Apotek,Tetap,APT054,PT Mitra Mandiri,YOGYAKARTA,2026-05-08,Friday,May,5,Q2,2026
3,FKT00004,20260321,PRD046,APT065,PLG017,KRY033,SUP085,3,41000,18400.0,104600,2600,KF-P0046,Oralit Sachet,Unknown,Kapsul,AlkesPro,SUP085,34000,KF-JAK065,Kimia Farma Jakarta Timur 65,Jakarta Timur,DKI Jakarta,Barat,MALL/COMMERCIAL,CUST00017,Budi Kusuma,L,61.0,>55,Palembang,Sumatera Selatan,Member,KF202600033,Tiara Permata,Kasir,Operasional Apotek,Kontrak,APT065,PT Anugerah Jaya,DENPASAR,2026-03-21,Saturday,March,3,Q1,2026
4,FKT00005,20260411,PRD052,APT061,PLG080,KRY086,SUP006,4,23500,0.0,94000,18000,KF-P0052,Glukosa Test Strip Care,Vitamin & Suplemen,Tablet,Kimia Farma,SUP006,19000,KF-SUR061,Kimia Farma Surabaya 61,Surabaya,Jawa Timur,Timur,Mall/Commercial,CUST00080,Miko Mahendra,L,45.0,36-45,Tangerang,Banten,BPJS/Asuransi,KF202600086,Fitri Mahendra,Unknown,Farmasi,Magang,APT022,PT Vita Mandiri,PEKANBARU,2026-04-11,Saturday,April,4,Q2,2026

In [22]:
# ============================================================
# CELL 21A: INSIGHT PRODUK TERLARIS
# ============================================================

produk_terlaris = (
    analyical_df
    .groupby("NamaProduk", as_index=False)
    .agg(
        Total_Terjual=("JumlahTerjual", "sum"),
        Total_Penjualan=("TotalPenjualan", "sum"),
        Total_Keuntungan=("Keuntungan", "sum")
    )
    .sort_values("Total_Penjualan", ascending=False)
    .head(10)
)

display(produk_terlaris)

                     NamaProduk  Total_Terjual  Total_Penjualan  Total_Keuntungan
48        Obat Flu Tablet Forte            142         11984300           2503800
66               Susu Kesehatan            102          7005300            891300
6   Asam Mefenamat 500mg Family             86          5868800            490800
23         Hand Sanitizer 100ml            105          5652200           1057700
21     Glukosa Test Strip Forte             83          5600800            634300
71           Termometer Digital             75          5035100            959100
55            Paracetamol 500mg             84          4758200            694200
20    Glukosa Test Strip Family             80          4632600            645100
62                  Salep Kulit             54          4579200            575200
64            Salep Kulit Forte             89          4070500            926500

In [23]:
# ============================================================
# CELL 21B: INSIGHT PENJUALAN PER KOTA
# ============================================================

penjualan_kota = (
    analyical_df
    .groupby("Kota", as_index=False)
    .agg(
        Total_Penjualan=("TotalPenjualan", "sum"),
        Total_Keuntungan=("Keuntungan", "sum"),
        Jumlah_Transaksi=("FakturID", "count")
    )
    .sort_values("Total_Penjualan", ascending=False)
)

display(penjualan_kota.head(10))

               Kota  Total_Penjualan  Total_Keuntungan  Jumlah_Transaksi
7     Jakarta Timur         32652100           5231100               182
16         Surabaya         15124500           2550000               116
1           Bandung         13438600           2184600                98
6   Jakarta Selatan         13180300           2000300                94
11           Padang          9992200           1586200                64
2            Bekasi          9063100           1391600                74
8          Makassar          6642900           1142900                40
4          Denpasar          6642500           1101500                53
0        Balikpapan          6179700            977700                34
5             Depok          5630100           1016100                29

In [24]:
# ============================================================
# CELL 21C: INSIGHT TREN PENJUALAN BULANAN
# ============================================================

tren_bulanan = (
    analyical_df
    .groupby(["Tahun", "NomorBulan", "Bulan"], as_index=False)
    .agg(
        Total_Penjualan=("TotalPenjualan", "sum"),
        Total_Keuntungan=("Keuntungan", "sum"),
        Jumlah_Transaksi=("FakturID", "count")
    )
    .sort_values(["Tahun", "NomorBulan"])
)

display(tren_bulanan)

    Tahun  NomorBulan      Bulan  Total_Penjualan  Total_Keuntungan  Jumlah_Transaksi
0    2026           1    January          9108500           1379500                63
1    2026           2   February          8856800           1501300                60
2    2026           3      March         11957800           1889300                78
3    2026           4      April         15982800           2468300               110
4    2026           5        May         14028200           1967700                96
5    2026           6       June         15236800           2525800                94
6    2026           7       July          7731800           1302800                62
7    2026           8     August          9416500           1540500                62
8    2026           9  September         11807500           1877500                77
9    2026          10    October         10938300           1578300                77
10   2026          11   November         13276800           2035800                97
11   2026          12   December         20997700           3810700               124

In [25]:
# ============================================================
# CELL 21D: INSIGHT SUPPLIER
# ============================================================

supplier_performance = (
    analyical_df
    .groupby("NamaSupplier", as_index=False)
    .agg(
        Total_Penjualan=("TotalPenjualan", "sum"),
        Total_Keuntungan=("Keuntungan", "sum"),
        Jumlah_Produk_Terjual=("JumlahTerjual", "sum")
    )
    .sort_values("Total_Penjualan", ascending=False)
)

display(supplier_performance.head(10))

            NamaSupplier  Total_Penjualan  Total_Keuntungan  Jumlah_Produk_Terjual
39     PT Medika Mandiri          8384100           1770600                    102
57    PT Sehat Kesehatan          6930400           1497900                    116
34         PT Indo Utama          6414800            567800                    128
17        PT Farma Utama          6057500            785500                    136
59    PT Sentosa Mandiri          5904400            709400                    114
5       PT Anugerah Jaya          5643100            860100                    142
60  PT Sentosa Sejahtera          5611700            714700                     90
68        PT Vita Medika          4533400            490900                     55
42    PT Mitra Indonesia          4009700            658200                    103
61      PT Sentosa Utama          3783300            500300                     55

In [26]:
# ============================================================
# CELL 21E: INSIGHT SEGMENTASI PELANGGAN
# ============================================================

if "KelompokUsia" in analyical_df.columns:
    segmentasi_usia = (
        analyical_df
        .groupby("KelompokUsia", as_index=False)
        .agg(
            Total_Penjualan=("TotalPenjualan", "sum"),
            Jumlah_Transaksi=("FakturID", "count")
        )
        .sort_values("Total_Penjualan", ascending=False)
    )

    display(segmentasi_usia)

if "JenisKelamin" in analyical_df.columns:
    segmentasi_gender = (
        analyical_df
        .groupby("JenisKelamin", as_index=False)
        .agg(
            Total_Penjualan=("TotalPenjualan", "sum"),
            Jumlah_Transaksi=("FakturID", "count")
        )
        .sort_values("Total_Penjualan", ascending=False)
    )

    display(segmentasi_gender)

/tmp/ipykernel_1995/3425646298.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby("KelompokUsia", as_index=False)

  KelompokUsia  Total_Penjualan  Jumlah_Transaksi
3        36-45         83301200               552
5          >55         28121700               202
2        26-35         17370700               109
1        18-25         11582200                74
4        46-55          8123500                55
0          <18           840200                 8

  JenisKelamin  Total_Penjualan  Jumlah_Transaksi
1            P         75280800               477
0            L         59283000               430
2      Unknown         14775700                93

In [27]:
# ============================================================
# CELL 21F: INSIGHT 1 - DEMOGRAFI & PRODUK (LANSIA + BPJS)
# Kategori produk apa yang paling banyak dibeli lansia pakai BPJS?
# ============================================================

# Memastikan kolom yang dibutuhkan tersedia
if all(col in analyical_df.columns for col in ["KelompokUsia", "TipePelanggan", "KategoriProduk", "TotalPenjualan"]):

    filter_lansia_bpjs = analyical_df[
        (analyical_df["KelompokUsia"].astype(str).str.contains(">55", na=False)) &
        (analyical_df["TipePelanggan"].astype(str).str.contains("BPJS/Asuransi", na=False, case=False))
    ]

    insight_demografi_produk = (
        filter_lansia_bpjs
        .groupby("KategoriProduk", as_index=False)
        .agg(
            Total_Penjualan=("TotalPenjualan", "sum"),
            Jumlah_Transaksi=("FakturID", "count")
        )
        .sort_values("Total_Penjualan", ascending=False)
    )

    print("Insight 1: Produk Favorit Lansia (>55) Pengguna BPJS")
    display(insight_demografi_produk)

Insight 1: Produk Favorit Lansia (>55) Pengguna BPJS

        KategoriProduk  Total_Penjualan  Jumlah_Transaksi
2           Obat Bebas          1648700                10
5   Vitamin & Suplemen           894300                 7
0       Alat Kesehatan           770000                 8
3  Perawatan Kesehatan           755800                 3
4              Unknown           622000                 5
1               Herbal           359700                 4

In [28]:
# ============================================================
# CELL 21G: INSIGHT 2 - GEOGRAFIS & PERFORMA CABANG
# Perbandingan margin (Keuntungan) Mall/Commercial vs Klinik di Jawa Barat
# ============================================================

if all(col in analyical_df.columns for col in ["Provinsi", "TipeCabang", "Keuntungan"]):

    filter_jabar_tipe = analyical_df[
        (analyical_df["Provinsi"].astype(str).str.contains("Jawa Barat", case=False, na=False)) &
        (analyical_df["TipeCabang"].isin(["Mall/Commercial", "Klinik Terintegrasi"]))
    ]

    insight_cabang_jabar = (
        filter_jabar_tipe
        .groupby("TipeCabang", as_index=False)
        .agg(
            Total_Keuntungan=("Keuntungan", "sum"),
            Rata_Rata_Keuntungan=("Keuntungan", "mean")
        )
        .sort_values("Total_Keuntungan", ascending=False)
    )

    print("Insight 2: Perbandingan Keuntungan Mall vs Klinik di Jawa Barat")
    display(insight_cabang_jabar)

Insight 2: Perbandingan Keuntungan Mall vs Klinik di Jawa Barat

            TipeCabang  Total_Keuntungan  Rata_Rata_Keuntungan
0  Klinik Terintegrasi           1290900          23470.909091
1      Mall/Commercial           1153900          24551.063830

In [29]:
# ============================================================
# CELL 21H: INSIGHT 3 - ANALISIS RANTAI PASOK (SUPPLIER)
# Supplier dengan kontribusi margin terbesar pada Q3 tahun ini
# ============================================================

if all(col in analyical_df.columns for col in ["NamaSupplier", "Kuartal", "Tahun", "Keuntungan"]):

    tahun_terbaru = analyical_df["Tahun"].max()

    filter_q3_tahun_ini = analyical_df[
        (analyical_df["Kuartal"] == "Q3") &
        (analyical_df["Tahun"] == tahun_terbaru)
    ]

    insight_supplier_q3 = (
        filter_q3_tahun_ini
        .groupby("NamaSupplier", as_index=False)
        .agg(
            Total_Keuntungan=("Keuntungan", "sum"),
            Jumlah_Item_Disuplai=("JumlahTerjual", "sum")
        )
        .sort_values("Total_Keuntungan", ascending=False)
        .head(5)
    )

    print(f"Insight 3: Top 5 Supplier Berdasarkan Keuntungan di Q3 Tahun {tahun_terbaru}")
    display(insight_supplier_q3)

Insight 3: Top 5 Supplier Berdasarkan Keuntungan di Q3 Tahun 2026

           NamaSupplier  Total_Keuntungan  Jumlah_Item_Disuplai
34    PT Medika Mandiri            322100                    17
5      PT Anugerah Jaya            269900                    48
49   PT Sehat Kesehatan            263200                    18
15   PT Farma Sejahtera            185500                    12
20  PT Global Kesehatan            156700                    10

In [30]:
# ============================================================
# CELL: QUERY SQL OLAP (DATA CUBE MENGGUNAKAN SQL)
# ============================================================
import pandas as pd

print("Menjalankan Query SQL OLAP menggunakan fungsi CUBE...")

# Query SQL OLAP dengan operasi CUBE untuk menghasilkan semua kombinasi agregasi
olap_sql_query = """
SELECT
    a."Wilayah",
    a."TipeCabang",
    w."Kuartal",
    SUM(f."TotalPenjualan") AS "Total_Penjualan",
    COUNT(f."FakturID") AS "Jumlah_Transaksi"
FROM fact_penjualan f
LEFT JOIN dim_apotek a ON f."ApotekID" = a."ApotekID"
LEFT JOIN dim_waktu w ON f."WaktuID" = w."WaktuID"
GROUP BY CUBE (a."Wilayah", a."TipeCabang", w."Kuartal")
ORDER BY
    a."Wilayah" NULLS LAST,
    a."TipeCabang" NULLS LAST,
    w."Kuartal" NULLS LAST;
"""

# Menjalankan query ke database Supabase (menggunakan objek engine yang sudah kamu buat sebelumnya)
try:
    df_olap_sql = pd.read_sql(olap_sql_query, con=engine)

    # Mengisi nilai NULL/None hasil operasi CUBE dengan label 'ALL' agar lebih mudah dibaca
    df_olap_sql["Wilayah"] = df_olap_sql["Wilayah"].fillna("ALL WILAYAH")
    df_olap_sql["TipeCabang"] = df_olap_sql["TipeCabang"].fillna("ALL TIPE")
    df_olap_sql["Kuartal"] = df_olap_sql["Kuartal"].fillna("ALL KUARTAL")

    # Format mata uang untuk kolom Total_Penjualan
    df_olap_sql["Total_Penjualan_Formatted"] = df_olap_sql["Total_Penjualan"].apply(lambda x: f"Rp {x:,.0f}".replace(",", "."))

    # Menampilkan 20 baris pertama sebagai sampel kuadrat data
    display(df_olap_sql[["Wilayah", "TipeCabang", "Kuartal", "Total_Penjualan_Formatted", "Jumlah_Transaksi"]].head(20))

except Exception as e:
    print("Gagal menjalankan query OLAP. Pastikan tabel di database sudah terisi.")
    print("Error:", e)

Menjalankan Query SQL OLAP menggunakan fungsi CUBE...
Gagal menjalankan query OLAP. Pastikan tabel di database sudah terisi.
Error: name 'engine' is not defined

In [31]:
# ============================================================
# CELL 22: LOAD / EXPORT HASIL ETL
# ============================================================

output_dir = "data_warehouse"
os.makedirs(output_dir, exist_ok=True)

dim_produk.to_csv(f"{output_dir}/dim_produk.csv", index=False)
dim_apotek.to_csv(f"{output_dir}/dim_apotek.csv", index=False)
dim_pelanggan.to_csv(f"{output_dir}/dim_pelanggan.csv", index=False)
dim_karyawan.to_csv(f"{output_dir}/dim_karyawan.csv", index=False)
dim_supplier.to_csv(f"{output_dir}/dim_supplier.csv", index=False)
dim_waktu.to_csv(f"{output_dir}/dim_waktu.csv", index=False)
fact_penjualan.to_csv(f"{output_dir}/fact_penjualan.csv", index=False)

print("Output ETL berhasil disimpan di folder:", output_dir)
print(os.listdir(output_dir))

Output ETL berhasil disimpan di folder: data_warehouse
['fact_penjualan.csv', 'dim_karyawan.csv', 'dim_produk.csv', 'dim_pelanggan.csv', 'dim_supplier.csv', 'dim_waktu.csv', 'dim_apotek.csv']

In [41]:
from sqlalchemy import create_engine, text

# 1. Masukkan Connection String dari Supabase
DB_URL = "postgresql://postgres.hudffdkqzckfayxpslun:Project_Datwer@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres"

# 2. Buat Engine Koneksi
engine = create_engine(DB_URL)

print("=== MEMULAI PROSES MIGRASI DATA TO SUPABASE ===")

# 3. AMANKAN RELASI: Hapus tabel fakta terlebih dahulu menggunakan DROP CASCADE via SQL mentah
# Langkah ini memotong paksa semua tali foreign key constraint yang mengunci tabel dimensi
with engine.connect() as connection:
    print("[LOG] Memutuskan constraint relasi dengan DROP TABLE... CASCADE...")
    connection.execute(text("DROP TABLE IF EXISTS fact_penjualan CASCADE;"))
    connection.execute(text("DROP TABLE IF EXISTS dim_pelanggan CASCADE;"))
    connection.execute(text("DROP TABLE IF EXISTS dim_produk CASCADE;"))
    connection.execute(text("DROP TABLE IF EXISTS dim_apotek CASCADE;"))
    connection.execute(text("DROP TABLE IF EXISTS dim_waktu CASCADE;"))
    connection.execute(text("DROP TABLE IF EXISTS dim_karyawan CASCADE;"))
    connection.execute(text("DROP TABLE IF EXISTS dim_supplier CASCADE;"))
    connection.commit()

# 4. Load Dataframe Dimensi ke Supabase (Sekarang dijamin 100% lancar dan lolos)
print("[LOG] Mengekspor Tabel Dimensi...")
dim_pelanggan.to_sql('dim_pelanggan', engine, if_exists='replace', index=False)
dim_produk.to_sql('dim_produk', engine, if_exists='replace', index=False)
dim_apotek.to_sql('dim_apotek', engine, if_exists='replace', index=False)
dim_waktu.to_sql('dim_waktu', engine, if_exists='replace', index=False)
dim_karyawan.to_sql('dim_karyawan', engine, if_exists='replace', index=False)
dim_supplier.to_sql('dim_supplier', engine, if_exists='replace', index=False)

# 5. Load Dataframe Fakta terakhir
print("[LOG] Mengekspor Tabel Fakta Penjualan...")
fact_penjualan.to_sql('fact_penjualan', engine, if_exists='replace', index=False)

print("Berhasil Export ke Supabase SQL!")

=== MEMULAI PROSES MIGRASI DATA TO SUPABASE ===
[LOG] Memutuskan constraint relasi dengan DROP TABLE... CASCADE...
[LOG] Mengekspor Tabel Dimensi...
[LOG] Mengekspor Tabel Fakta Penjualan...
Berhasil Export ke Supabase SQL!

In [37]:
# ============================================================
# CELL 23: ZIP DAN DOWNLOAD OUTPUT ETL
# ============================================================

import shutil

zip_name = "kimia_farma_data_warehouse_output"
shutil.make_archive(zip_name, "zip", output_dir)

files.download(f"{zip_name}.zip")

print("File ZIP siap didownload.")

File ZIP siap didownload.